//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabDesk.Code.GestorSonido {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosSound {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosSound() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LabDesk.Code.GestorSonido.RecursosSound", typeof(RecursosSound).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string Advertencia {
            get {
                return ResourceManager.GetString("Advertencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string ClickBtnUI {
            get {
                return ResourceManager.GetString("ClickBtnUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string Confirmacion {
            get {
                return ResourceManager.GetString("Confirmacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string FinalSesion {
            get {
                return ResourceManager.GetString("FinalSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string InicioSesion {
            get {
                return ResourceManager.GetString("InicioSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string TestVol {
            get {
                return ResourceManager.GetString("TestVol", resourceCulture);
            }
        }
    }
}
