//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabDesk.Code.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosUIMensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosUIMensajes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LabDesk.Code.Forms.RecursosUIMensajes", typeof(RecursosUIMensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string MsgAdvertencia {
            get {
                return ResourceManager.GetString("MsgAdvertencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string MsgAnalisisError {
            get {
                return ResourceManager.GetString("MsgAnalisisError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string MsgConexionError {
            get {
                return ResourceManager.GetString("MsgConexionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string MsgConfirmacion {
            get {
                return ResourceManager.GetString("MsgConfirmacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string MsgCuentaUpdate {
            get {
                return ResourceManager.GetString("MsgCuentaUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string MsgCuentaValidation1 {
            get {
                return ResourceManager.GetString("MsgCuentaValidation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string MsgCuentaValidation2 {
            get {
                return ResourceManager.GetString("MsgCuentaValidation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string MsgCuentaValidation3 {
            get {
                return ResourceManager.GetString("MsgCuentaValidation3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string MsgImpresionError {
            get {
                return ResourceManager.GetString("MsgImpresionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string MsgMedicoNoEncontrados {
            get {
                return ResourceManager.GetString("MsgMedicoNoEncontrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string MsgMedicoNoSeleccionado {
            get {
                return ResourceManager.GetString("MsgMedicoNoSeleccionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string MsgNone {
            get {
                return ResourceManager.GetString("MsgNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string MsgOrdenDeleteDesicion {
            get {
                return ResourceManager.GetString("MsgOrdenDeleteDesicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string MsgOrdenError1 {
            get {
                return ResourceManager.GetString("MsgOrdenError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string MsgOrdenError2 {
            get {
                return ResourceManager.GetString("MsgOrdenError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string MsgOrdenOk {
            get {
                return ResourceManager.GetString("MsgOrdenOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string MsgOrdenSave {
            get {
                return ResourceManager.GetString("MsgOrdenSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string MsgOrdenUnsave {
            get {
                return ResourceManager.GetString("MsgOrdenUnsave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string MsgPeligro {
            get {
                return ResourceManager.GetString("MsgPeligro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string MsgPerfilDelete {
            get {
                return ResourceManager.GetString("MsgPerfilDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string MsgPerfilDeleteDesicion {
            get {
                return ResourceManager.GetString("MsgPerfilDeleteDesicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string MsgPerfilOk {
            get {
                return ResourceManager.GetString("MsgPerfilOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string MsgPerfilSave {
            get {
                return ResourceManager.GetString("MsgPerfilSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string MsgPerfilUnsave {
            get {
                return ResourceManager.GetString("MsgPerfilUnsave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string MsgPrincipalClose {
            get {
                return ResourceManager.GetString("MsgPrincipalClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string MsgReporteOk {
            get {
                return ResourceManager.GetString("MsgReporteOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string MsgTarifarioCloseAsk {
            get {
                return ResourceManager.GetString("MsgTarifarioCloseAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string MsgTarifarioCopy {
            get {
                return ResourceManager.GetString("MsgTarifarioCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string MsgTarifarioCopyError {
            get {
                return ResourceManager.GetString("MsgTarifarioCopyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string MsgTarifarioEditError {
            get {
                return ResourceManager.GetString("MsgTarifarioEditError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string MsgTarifarioNuevoError {
            get {
                return ResourceManager.GetString("MsgTarifarioNuevoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string MsgTarifarioNuevoOk {
            get {
                return ResourceManager.GetString("MsgTarifarioNuevoOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string MsgTarifarioSave {
            get {
                return ResourceManager.GetString("MsgTarifarioSave", resourceCulture);
            }
        }
    }
}
