//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabDesk.Code.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LabDesk.Code.Forms.RecursosUI", typeof(RecursosUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIConfig1 {
            get {
                return ResourceManager.GetString("BtnUIConfig1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIConfig2 {
            get {
                return ResourceManager.GetString("BtnUIConfig2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIConfig3 {
            get {
                return ResourceManager.GetString("BtnUIConfig3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIConfig4 {
            get {
                return ResourceManager.GetString("BtnUIConfig4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIConfig5 {
            get {
                return ResourceManager.GetString("BtnUIConfig5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIConfig6 {
            get {
                return ResourceManager.GetString("BtnUIConfig6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIContabilidad1 {
            get {
                return ResourceManager.GetString("BtnUIContabilidad1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIExamen1 {
            get {
                return ResourceManager.GetString("BtnUIExamen1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIExamenEditor1 {
            get {
                return ResourceManager.GetString("BtnUIExamenEditor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIExamenEditor2 {
            get {
                return ResourceManager.GetString("BtnUIExamenEditor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIMain1 {
            get {
                return ResourceManager.GetString("BtnUIMain1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIMain2 {
            get {
                return ResourceManager.GetString("BtnUIMain2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIMain3 {
            get {
                return ResourceManager.GetString("BtnUIMain3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIMain4 {
            get {
                return ResourceManager.GetString("BtnUIMain4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIMain5 {
            get {
                return ResourceManager.GetString("BtnUIMain5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIMain6 {
            get {
                return ResourceManager.GetString("BtnUIMain6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIMain7 {
            get {
                return ResourceManager.GetString("BtnUIMain7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIMain8 {
            get {
                return ResourceManager.GetString("BtnUIMain8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIMain9 {
            get {
                return ResourceManager.GetString("BtnUIMain9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIMedicoBuscar1 {
            get {
                return ResourceManager.GetString("BtnUIMedicoBuscar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIMedicoBuscar2 {
            get {
                return ResourceManager.GetString("BtnUIMedicoBuscar2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIMedicoEditar1 {
            get {
                return ResourceManager.GetString("BtnUIMedicoEditar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIMedicoEditar2 {
            get {
                return ResourceManager.GetString("BtnUIMedicoEditar2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIMedicoEditar3 {
            get {
                return ResourceManager.GetString("BtnUIMedicoEditar3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIMedicoNuevo1 {
            get {
                return ResourceManager.GetString("BtnUIMedicoNuevo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIMedicoNuevo2 {
            get {
                return ResourceManager.GetString("BtnUIMedicoNuevo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIOrdenBuscar1 {
            get {
                return ResourceManager.GetString("BtnUIOrdenBuscar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIOrdenBuscar2 {
            get {
                return ResourceManager.GetString("BtnUIOrdenBuscar2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIOrdenEditar1 {
            get {
                return ResourceManager.GetString("BtnUIOrdenEditar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIOrdenEditar2 {
            get {
                return ResourceManager.GetString("BtnUIOrdenEditar2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIOrdenEditar3 {
            get {
                return ResourceManager.GetString("BtnUIOrdenEditar3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIOrdenNuevo1 {
            get {
                return ResourceManager.GetString("BtnUIOrdenNuevo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIOrdenNuevo2 {
            get {
                return ResourceManager.GetString("BtnUIOrdenNuevo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIOrdenNuevo3 {
            get {
                return ResourceManager.GetString("BtnUIOrdenNuevo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIOrdenPerfil1 {
            get {
                return ResourceManager.GetString("BtnUIOrdenPerfil1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIOrdenPerfil2 {
            get {
                return ResourceManager.GetString("BtnUIOrdenPerfil2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIPacienteBuscar1 {
            get {
                return ResourceManager.GetString("BtnUIPacienteBuscar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIPacienteBuscar2 {
            get {
                return ResourceManager.GetString("BtnUIPacienteBuscar2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIPacienteEditar1 {
            get {
                return ResourceManager.GetString("BtnUIPacienteEditar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIPacienteEditar2 {
            get {
                return ResourceManager.GetString("BtnUIPacienteEditar2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIPacienteEditar3 {
            get {
                return ResourceManager.GetString("BtnUIPacienteEditar3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIPacienteNuevo1 {
            get {
                return ResourceManager.GetString("BtnUIPacienteNuevo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIPacienteNuevo2 {
            get {
                return ResourceManager.GetString("BtnUIPacienteNuevo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUISesion1 {
            get {
                return ResourceManager.GetString("BtnUISesion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUITarifarioCopia1 {
            get {
                return ResourceManager.GetString("BtnUITarifarioCopia1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUITarifarioNuevo1 {
            get {
                return ResourceManager.GetString("BtnUITarifarioNuevo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIUsuarioClave1 {
            get {
                return ResourceManager.GetString("BtnUIUsuarioClave1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIUsuarioClave2 {
            get {
                return ResourceManager.GetString("BtnUIUsuarioClave2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIUsuarioDatos1 {
            get {
                return ResourceManager.GetString("BtnUIUsuarioDatos1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIUsuarioDatos2 {
            get {
                return ResourceManager.GetString("BtnUIUsuarioDatos2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIUsuarioNuevo1 {
            get {
                return ResourceManager.GetString("BtnUIUsuarioNuevo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnUIUsuarioNuevo2 {
            get {
                return ResourceManager.GetString("BtnUIUsuarioNuevo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string ControlBienvenida {
            get {
                return ResourceManager.GetString("ControlBienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string ControlContabilidad {
            get {
                return ResourceManager.GetString("ControlContabilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string ControlExamen {
            get {
                return ResourceManager.GetString("ControlExamen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string ControlMedico {
            get {
                return ResourceManager.GetString("ControlMedico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string ControlOrden {
            get {
                return ResourceManager.GetString("ControlOrden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string ControlPaciente {
            get {
                return ResourceManager.GetString("ControlPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string PanelMedicoEditar {
            get {
                return ResourceManager.GetString("PanelMedicoEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string PanelMedicoNuevo {
            get {
                return ResourceManager.GetString("PanelMedicoNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string PanelMedicoPerfil {
            get {
                return ResourceManager.GetString("PanelMedicoPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string PanelOrdenEditar {
            get {
                return ResourceManager.GetString("PanelOrdenEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string PanelOrdenNuevo {
            get {
                return ResourceManager.GetString("PanelOrdenNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string PanelOrdenPerfil {
            get {
                return ResourceManager.GetString("PanelOrdenPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string PanelPacienteEditar {
            get {
                return ResourceManager.GetString("PanelPacienteEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string PanelPacienteNuevo {
            get {
                return ResourceManager.GetString("PanelPacienteNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string PanelPacientePerfil {
            get {
                return ResourceManager.GetString("PanelPacientePerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string PanelUIMedicoBuscar1 {
            get {
                return ResourceManager.GetString("PanelUIMedicoBuscar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string PanelUIUsuarioClave1 {
            get {
                return ResourceManager.GetString("PanelUIUsuarioClave1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string PanelUIUsuarioDatos1 {
            get {
                return ResourceManager.GetString("PanelUIUsuarioDatos1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string Propietario {
            get {
                return ResourceManager.GetString("Propietario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string SistemaName {
            get {
                return ResourceManager.GetString("SistemaName", resourceCulture);
            }
        }
    }
}
