//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabDesk.Code.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosUIToolkit {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosUIToolkit() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LabDesk.Code.Forms.RecursosUIToolkit", typeof(RecursosUIToolkit).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnExamenEditarCerrar {
            get {
                return ResourceManager.GetString("BtnExamenEditarCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnExamenEditarGuardar {
            get {
                return ResourceManager.GetString("BtnExamenEditarGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnOrdenAbrir {
            get {
                return ResourceManager.GetString("BtnOrdenAbrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnOrdenEditarGuardar {
            get {
                return ResourceManager.GetString("BtnOrdenEditarGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnOrdenNuevo {
            get {
                return ResourceManager.GetString("BtnOrdenNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnOrdenNuevoAgregarExamen {
            get {
                return ResourceManager.GetString("BtnOrdenNuevoAgregarExamen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnOrdenNuevoAgregarPaciente {
            get {
                return ResourceManager.GetString("BtnOrdenNuevoAgregarPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnOrdenNuevoCerrar {
            get {
                return ResourceManager.GetString("BtnOrdenNuevoCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnOrdenNuevoEliminarExamen {
            get {
                return ResourceManager.GetString("BtnOrdenNuevoEliminarExamen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnPerfilAbrir {
            get {
                return ResourceManager.GetString("BtnPerfilAbrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnPerfilCerrar {
            get {
                return ResourceManager.GetString("BtnPerfilCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnPerfilEditar {
            get {
                return ResourceManager.GetString("BtnPerfilEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnPerfilEditarCerrar {
            get {
                return ResourceManager.GetString("BtnPerfilEditarCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnPerfilEditarGuardar {
            get {
                return ResourceManager.GetString("BtnPerfilEditarGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnPerfilNuevo {
            get {
                return ResourceManager.GetString("BtnPerfilNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnPerfilNuevoCerrar {
            get {
                return ResourceManager.GetString("BtnPerfilNuevoCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnPerfilPrintExamen {
            get {
                return ResourceManager.GetString("BtnPerfilPrintExamen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnTarifarioModificar {
            get {
                return ResourceManager.GetString("BtnTarifarioModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnTarifarioNuevo {
            get {
                return ResourceManager.GetString("BtnTarifarioNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnTarifarioSave {
            get {
                return ResourceManager.GetString("BtnTarifarioSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string BtnTarifarioTransferir {
            get {
                return ResourceManager.GetString("BtnTarifarioTransferir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible transferir la información.
        /// </summary>
        internal static string CheckBoxTarifarioVigente {
            get {
                return ResourceManager.GetString("CheckBoxTarifarioVigente", resourceCulture);
            }
        }
    }
}
