
using LabDesk.Code.Base;
using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace LabDesk.Code.Components.Laboratory.Orden
{
    partial class PanelOrdenNuevo
    {
        /// <summary> 
        /// Variable del diseñador necesaria.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Limpiar los recursos que se estén usando.
        /// </summary>
        /// <param name="disposing">true si los recursos administrados se deben desechar; false en caso contrario.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Código generado por el Diseñador de componentes

        /// <summary> 
        /// Método necesario para admitir el Diseñador. No se puede modificar
        /// el contenido de este método con el editor de código.
        /// </summary>

        private void InitializeComponent()
        {
            DataGridViewCellStyle style = new DataGridViewCellStyle();
            DataGridViewCellStyle style2 = new DataGridViewCellStyle();
            this.PickerTime = new DateTimePicker();
            this.PanelBarTable = new Panel();
            this.BtnOrdenNuevoEliminarExamen = new Button();
            this.BtnOrdenNuevoAgregarExamen = new Button();
            this.LabelNombreExamen = new Label();
            this.ComboExamen = new ComboBox();
            this.label7 = new Label();
            this.CampUbicacion = new Label();
            this.label9 = new Label();
            this.CampHistoria = new Label();
            this.CampDni = new Label();
            this.CampNombre = new Label();
            this.dataGridView = new DataGridView();
            this.id = new DataGridViewTextBoxColumn();
            this.codigo = new DataGridViewTextBoxColumn();
            this.nombre = new DataGridViewTextBoxColumn();
            this.cobertura = new DataGridViewComboBoxColumn();
            this.idUnique = new DataGridViewTextBoxColumn();
            this.label1 = new Label();
            this.CampBoleta = new TextBox();
            this.label12 = new Label();
            this.label10 = new Label();
            this.label8 = new Label();
            this.label4 = new Label();
            this.label3 = new Label();
            this.CheckBoxGestante = new CheckBox();
            this.CampSexo = new Label();
            this.label6 = new Label();
            this.ComboBoxConsultorio = new ComboBox();
            this.ComboBoxMedico = new ComboBox();
            this.label5 = new Label();
            this.label11 = new Label();
            this.label2 = new Label();
            this.BtnUIOrdenNuevo2 = new ButtonUI();
            this.BtnOrdenNuevoCerrar = new Button();
            this.BtnOrdenNuevoAgregarPaciente = new Button();
            this.PanelBarTable.SuspendLayout();
            ((ISupportInitialize)this.dataGridView).BeginInit();
            base.SuspendLayout();
            this.PickerTime.CalendarFont = new Font("Futura Bk BT", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.PickerTime.Format = DateTimePickerFormat.Short;
            this.PickerTime.Location = new Point(0x3a8, 0xac);
            this.PickerTime.Name = "PickerTime";
            this.PickerTime.Size = new Size(0x6c, 20);
            this.PickerTime.TabIndex = 0x60;
            this.PanelBarTable.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Top;
            this.PanelBarTable.BackColor = Color.SteelBlue;
            this.PanelBarTable.Controls.Add(this.BtnOrdenNuevoEliminarExamen);
            this.PanelBarTable.Controls.Add(this.BtnOrdenNuevoAgregarExamen);
            this.PanelBarTable.Controls.Add(this.LabelNombreExamen);
            this.PanelBarTable.Controls.Add(this.ComboExamen);
            this.PanelBarTable.Location = new Point(0x20, 0xef);
            this.PanelBarTable.Margin = new Padding(0);
            this.PanelBarTable.Name = "PanelBarTable";
            this.PanelBarTable.Size = new Size(0x3f5, 0x21);
            this.PanelBarTable.TabIndex = 0x5f;
            this.BtnOrdenNuevoEliminarExamen.Anchor = AnchorStyles.Right | AnchorStyles.Top;
            this.BtnOrdenNuevoEliminarExamen.BackColor = Color.Transparent;
            this.BtnOrdenNuevoEliminarExamen.FlatAppearance.BorderSize = 0;
            this.BtnOrdenNuevoEliminarExamen.FlatAppearance.CheckedBackColor = Color.DeepSkyBlue;
            this.BtnOrdenNuevoEliminarExamen.FlatStyle = FlatStyle.Flat;
            this.BtnOrdenNuevoEliminarExamen.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.BtnOrdenNuevoEliminarExamen.ForeColor = SystemColors.Info;
            //this.BtnOrdenNuevoEliminarExamen.Image = Resources.icon_eliminar;
            this.BtnOrdenNuevoEliminarExamen.ImageAlign = ContentAlignment.MiddleLeft;
            this.BtnOrdenNuevoEliminarExamen.Location = new Point(0x3d6, 5);
            this.BtnOrdenNuevoEliminarExamen.Name = "BtnOrdenNuevoEliminarExamen";
            this.BtnOrdenNuevoEliminarExamen.Size = new Size(0x1a, 0x18);
            this.BtnOrdenNuevoEliminarExamen.TabIndex = 0x47;
            this.BtnOrdenNuevoEliminarExamen.TextAlign = ContentAlignment.MiddleRight;
            this.BtnOrdenNuevoEliminarExamen.UseVisualStyleBackColor = false;
            this.BtnOrdenNuevoEliminarExamen.Click += new EventHandler(this.BtnEliminar_Click);
            this.BtnOrdenNuevoAgregarExamen.BackColor = Color.Transparent;
            this.BtnOrdenNuevoAgregarExamen.BackgroundImageLayout = ImageLayout.None;
            this.BtnOrdenNuevoAgregarExamen.FlatAppearance.BorderSize = 0;
            this.BtnOrdenNuevoAgregarExamen.FlatStyle = FlatStyle.Flat;
            this.BtnOrdenNuevoAgregarExamen.Font = new Font("Futura Bk BT", 11.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.BtnOrdenNuevoAgregarExamen.ForeColor = Color.Transparent;
            //this.BtnOrdenNuevoAgregarExamen.Image = Resources.icon_agregar;
            this.BtnOrdenNuevoAgregarExamen.Location = new Point(0x184, 5);
            this.BtnOrdenNuevoAgregarExamen.Margin = new Padding(0);
            this.BtnOrdenNuevoAgregarExamen.Name = "BtnOrdenNuevoAgregarExamen";
            this.BtnOrdenNuevoAgregarExamen.Size = new Size(0x1a, 0x18);
            this.BtnOrdenNuevoAgregarExamen.TabIndex = 0x3d;
            this.BtnOrdenNuevoAgregarExamen.UseVisualStyleBackColor = false;
            this.BtnOrdenNuevoAgregarExamen.Click += new EventHandler(this.BtnAgregar_Click);
            this.LabelNombreExamen.AutoSize = true;
            this.LabelNombreExamen.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelNombreExamen.ForeColor = SystemColors.Window;
            this.LabelNombreExamen.Location = new Point(12, 8);
            this.LabelNombreExamen.Name = "LabelNombreExamen";
            this.LabelNombreExamen.Size = new Size(0x39, 0x10);
            this.LabelNombreExamen.TabIndex = 0x3b;
            this.LabelNombreExamen.Text = "Examen:";
            this.ComboExamen.AutoCompleteMode = AutoCompleteMode.Suggest;
            this.ComboExamen.AutoCompleteSource = AutoCompleteSource.ListItems;
            this.ComboExamen.FlatStyle = FlatStyle.Flat;
            this.ComboExamen.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.ComboExamen.FormattingEnabled = true;
            this.ComboExamen.Location = new Point(0x52, 5);
            this.ComboExamen.Margin = new Padding(0);
            this.ComboExamen.Name = "ComboExamen";
            this.ComboExamen.Size = new Size(0x130, 0x18);
            this.ComboExamen.TabIndex = 0x3e;
            this.label7.AutoSize = true;
            this.label7.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label7.Location = new Point(800, 0xae);
            this.label7.Name = "label7";
            this.label7.Size = new Size(0x2c, 0x10);
            this.label7.TabIndex = 0x5e;
            this.label7.Text = "(Opc.)";
            this.CampUbicacion.AutoSize = true;
            this.CampUbicacion.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.CampUbicacion.Location = new Point(0x62, 0x88);
            this.CampUbicacion.Name = "CampUbicacion";
            this.CampUbicacion.Size = new Size(0x1b, 0x10);
            this.CampUbicacion.TabIndex = 0x5d;
            this.CampUbicacion.Text = "asd";
            this.label9.AutoSize = true;
            this.label9.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label9.Location = new Point(0x1d, 0x88);
            this.label9.Name = "label9";
            this.label9.Size = new Size(0x43, 0x10);
            this.label9.TabIndex = 0x5c;
            this.label9.Text = "Ubicacion:";
            this.CampHistoria.AutoSize = true;
            this.CampHistoria.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.CampHistoria.Location = new Point(0x119, 0x62);
            this.CampHistoria.Name = "CampHistoria";
            this.CampHistoria.Size = new Size(0x33, 0x10);
            this.CampHistoria.TabIndex = 90;
            this.CampHistoria.Text = "label11";
            this.CampDni.AutoSize = true;
            this.CampDni.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.CampDni.Location = new Point(0x62, 0x62);
            this.CampDni.Name = "CampDni";
            this.CampDni.Size = new Size(0x2b, 0x10);
            this.CampDni.TabIndex = 0x59;
            this.CampDni.Text = "label9";
            this.CampNombre.AutoSize = true;
            this.CampNombre.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.CampNombre.Location = new Point(0x62, 60);
            this.CampNombre.Name = "CampNombre";
            this.CampNombre.Size = new Size(0x2b, 0x10);
            this.CampNombre.TabIndex = 0x58;
            this.CampNombre.Text = "label7";
            this.dataGridView.AllowUserToAddRows = false;
            this.dataGridView.AllowUserToDeleteRows = false;
            this.dataGridView.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Bottom | AnchorStyles.Top;
            this.dataGridView.BackgroundColor = SystemColors.ScrollBar;
            this.dataGridView.BorderStyle = BorderStyle.None;
            this.dataGridView.CellBorderStyle = DataGridViewCellBorderStyle.SingleVertical;
            this.dataGridView.ColumnHeadersBorderStyle = DataGridViewHeaderBorderStyle.Single;
            style.Alignment = DataGridViewContentAlignment.MiddleCenter;
            style.BackColor = SystemColors.Control;
            style.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            style.ForeColor = SystemColors.WindowText;
            style.SelectionBackColor = SystemColors.GrayText;
            style.SelectionForeColor = SystemColors.HighlightText;
            style.WrapMode = DataGridViewTriState.True;
            this.dataGridView.ColumnHeadersDefaultCellStyle = style;
            this.dataGridView.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            DataGridViewColumn[] dataGridViewColumns = new DataGridViewColumn[] { this.id, this.codigo, this.nombre, this.cobertura, this.idUnique };
            this.dataGridView.Columns.AddRange(dataGridViewColumns);
            this.dataGridView.Location = new Point(0x20, 0x110);
            this.dataGridView.Margin = new Padding(0);
            this.dataGridView.Name = "dataGridView";
            style2.Alignment = DataGridViewContentAlignment.MiddleLeft;
            style2.BackColor = SystemColors.Control;
            style2.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            style2.ForeColor = SystemColors.WindowText;
            style2.SelectionBackColor = SystemColors.Highlight;
            style2.SelectionForeColor = SystemColors.HighlightText;
            style2.WrapMode = DataGridViewTriState.True;
            this.dataGridView.RowHeadersDefaultCellStyle = style2;
            this.dataGridView.Size = new Size(0x3f5, 0xc6);
            this.dataGridView.TabIndex = 0x57;
            this.id.HeaderText = "Id";
            this.id.Name = "id";
            this.id.Visible = false;
            this.codigo.HeaderText = "Codigo";
            this.codigo.Name = "codigo";
            this.nombre.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            this.nombre.HeaderText = "Nombre";
            this.nombre.Name = "nombre";
            this.cobertura.HeaderText = "Cobertura";
            this.cobertura.Name = "cobertura";
            this.cobertura.Resizable = DataGridViewTriState.True;
            this.cobertura.SortMode = DataGridViewColumnSortMode.Automatic;
            this.idUnique.HeaderText = "idUnique";
            this.idUnique.Name = "idUnique";
            this.idUnique.Visible = false;
            this.label1.AutoSize = true;
            this.label1.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label1.Location = new Point(0x27a, 0xae);
            this.label1.Name = "label1";
            this.label1.Size = new Size(0x2e, 0x10);
            this.label1.TabIndex = 0x55;
            this.label1.Text = "Boleta:";
            this.CampBoleta.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.CampBoleta.Location = new Point(0x2ae, 0xab);
            this.CampBoleta.Name = "CampBoleta";
            this.CampBoleta.Size = new Size(0x6c, 0x17);
            this.CampBoleta.TabIndex = 0x54;
            this.label12.AutoSize = true;
            this.label12.Font = new Font("Futura Bk BT", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label12.Location = new Point(0x1c, 0x1c);
            this.label12.Name = "label12";
            this.label12.Size = new Size(0x9c, 0x13);
            this.label12.TabIndex = 0x53;
            this.label12.Text = "Informaci\x00f3n General";
            this.label10.AutoSize = true;
            this.label10.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label10.Location = new Point(0xdd, 0x62);
            this.label10.Name = "label10";
            this.label10.Size = new Size(0x36, 0x10);
            this.label10.TabIndex = 0x4d;
            this.label10.Text = "Historia:";
            this.label8.AutoSize = true;
            this.label8.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label8.Location = new Point(0x1d, 0x62);
            this.label8.Name = "label8";
            this.label8.Size = new Size(0x22, 0x10);
            this.label8.TabIndex = 0x4c;
            this.label8.Text = "DNI:";
            this.label4.AutoSize = true;
            this.label4.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label4.Location = new Point(0x1d, 60);
            this.label4.Name = "label4";
            this.label4.Size = new Size(0x3b, 0x10);
            this.label4.TabIndex = 0x4b;
            this.label4.Text = "Nombre:";
            this.label3.AutoSize = true;
            this.label3.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label3.Location = new Point(0x36b, 0xae);
            this.label3.Name = "label3";
            this.label3.Size = new Size(0x2e, 0x10);
            this.label3.TabIndex = 0x4f;
            this.label3.Text = "Fecha:";
            this.CheckBoxGestante.AutoSize = true;
            this.CheckBoxGestante.Font = new Font("Futura Bk BT", 9.25f);
            this.CheckBoxGestante.Location = new Point(0x24a, 0x60);
            this.CheckBoxGestante.Name = "CheckBoxGestante";
            this.CheckBoxGestante.RightToLeft = RightToLeft.Yes;
            this.CheckBoxGestante.Size = new Size(0x70, 20);
            this.CheckBoxGestante.TabIndex = 0x93;
            this.CheckBoxGestante.Text = ":En Gestancion";
            this.CheckBoxGestante.TextAlign = ContentAlignment.MiddleRight;
            this.CheckBoxGestante.UseVisualStyleBackColor = true;
            this.CampSexo.AutoSize = true;
            this.CampSexo.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.CampSexo.Location = new Point(0x1d5, 0x62);
            this.CampSexo.Name = "CampSexo";
            this.CampSexo.Size = new Size(0x33, 0x10);
            this.CampSexo.TabIndex = 0x95;
            this.CampSexo.Text = "label11";
            this.label6.AutoSize = true;
            this.label6.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label6.Location = new Point(0x199, 0x62);
            this.label6.Name = "label6";
            this.label6.Size = new Size(0x27, 0x10);
            this.label6.TabIndex = 0x94;
            this.label6.Text = "Sexo:";
            this.ComboBoxConsultorio.DropDownStyle = ComboBoxStyle.DropDownList;
            this.ComboBoxConsultorio.FormattingEnabled = true;
            this.ComboBoxConsultorio.Location = new Point(0x17b, 0xac);
            this.ComboBoxConsultorio.Name = "ComboBoxConsultorio";
            this.ComboBoxConsultorio.Size = new Size(0xde, 0x15);
            this.ComboBoxConsultorio.TabIndex = 150;
            this.ComboBoxMedico.DropDownStyle = ComboBoxStyle.DropDownList;
            this.ComboBoxMedico.FormattingEnabled = true;
            this.ComboBoxMedico.Location = new Point(0x65, 0xac);
            this.ComboBoxMedico.Name = "ComboBoxMedico";
            this.ComboBoxMedico.Size = new Size(0xab, 0x15);
            this.ComboBoxMedico.TabIndex = 0x97;
            this.label5.AutoSize = true;
            this.label5.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label5.Location = new Point(0x1d, 0xae);
            this.label5.Name = "label5";
            this.label5.Size = new Size(0x35, 0x10);
            this.label5.TabIndex = 0x98;
            this.label5.Text = "Medico:";
            this.label11.AutoSize = true;
            this.label11.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label11.Location = new Point(0x120, 0xae);
            this.label11.Name = "label11";
            this.label11.Size = new Size(0x4b, 0x10);
            this.label11.TabIndex = 0x99;
            this.label11.Text = "Consultorio:";
            this.label2.AutoSize = true;
            this.label2.Font = new Font("Futura Bk BT", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label2.Location = new Point(0x1c, 0xd1);
            this.label2.Name = "label2";
            this.label2.Size = new Size(0x9e, 0x13);
            this.label2.TabIndex = 0xc5;
            this.label2.Text = "Examenes Solicitados";
            this.label2.TextAlign = ContentAlignment.MiddleLeft;
            this.BtnUIOrdenNuevo2.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            this.BtnUIOrdenNuevo2.BackColor = SystemColors.ActiveCaptionText;
            this.BtnUIOrdenNuevo2.Location = new Point(0x3a5, 0x1e5);
            this.BtnUIOrdenNuevo2.Margin = new Padding(0);
            this.BtnUIOrdenNuevo2.Name = "BtnUIOrdenNuevo2";
            this.BtnUIOrdenNuevo2.Size = new Size(0x70, 40);
            this.BtnUIOrdenNuevo2.TabIndex = 0xc7;
            this.BtnOrdenNuevoCerrar.Anchor = AnchorStyles.Right | AnchorStyles.Top;
            this.BtnOrdenNuevoCerrar.FlatAppearance.BorderColor = Color.DimGray;
            this.BtnOrdenNuevoCerrar.FlatAppearance.BorderSize = 0;
            this.BtnOrdenNuevoCerrar.FlatStyle = FlatStyle.Flat;
            this.BtnOrdenNuevoCerrar.Font = new Font("Futura Bk BT", 8.25f);
            this.BtnOrdenNuevoCerrar.ForeColor = SystemColors.Window;
            //this.BtnOrdenNuevoCerrar.Image = Resources.icon_cerrar;
            this.BtnOrdenNuevoCerrar.Location = new Point(0x412, 12);
            this.BtnOrdenNuevoCerrar.Margin = new Padding(0);
            this.BtnOrdenNuevoCerrar.Name = "BtnOrdenNuevoCerrar";
            this.BtnOrdenNuevoCerrar.Padding = new Padding(5);
            this.BtnOrdenNuevoCerrar.Size = new Size(20, 20);
            this.BtnOrdenNuevoCerrar.TabIndex = 0xe9;
            this.BtnOrdenNuevoCerrar.TextAlign = ContentAlignment.MiddleLeft;
            this.BtnOrdenNuevoCerrar.TextImageRelation = TextImageRelation.ImageBeforeText;
            this.BtnOrdenNuevoCerrar.UseVisualStyleBackColor = false;
            this.BtnOrdenNuevoCerrar.Click += new EventHandler(this.BtnPerfilCerrar_Click);
            this.BtnOrdenNuevoAgregarPaciente.Anchor = AnchorStyles.Right | AnchorStyles.Top;
            this.BtnOrdenNuevoAgregarPaciente.FlatAppearance.BorderColor = Color.SteelBlue;
            this.BtnOrdenNuevoAgregarPaciente.FlatAppearance.BorderSize = 0;
            this.BtnOrdenNuevoAgregarPaciente.FlatStyle = FlatStyle.Flat;
            this.BtnOrdenNuevoAgregarPaciente.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.BtnOrdenNuevoAgregarPaciente.ForeColor = SystemColors.ControlLightLight;
            //this.BtnOrdenNuevoAgregarPaciente.Image = Resources.icon_buscar_paciente;
            this.BtnOrdenNuevoAgregarPaciente.Location = new Point(0x3fc, 60);
            this.BtnOrdenNuevoAgregarPaciente.Margin = new Padding(0);
            this.BtnOrdenNuevoAgregarPaciente.Name = "BtnOrdenNuevoAgregarPaciente";
            this.BtnOrdenNuevoAgregarPaciente.Size = new Size(0x19, 0x19);
            this.BtnOrdenNuevoAgregarPaciente.TabIndex = 0xc9;
            this.BtnOrdenNuevoAgregarPaciente.UseVisualStyleBackColor = false;
            this.BtnOrdenNuevoAgregarPaciente.Click += new EventHandler(this.button1_Click);
            base.AutoScaleDimensions = new SizeF(6f, 13f);
            base.AutoScaleMode = AutoScaleMode.Font;
            this.BackColor = SystemColors.Window;
            base.Controls.Add(this.BtnOrdenNuevoCerrar);
            base.Controls.Add(this.BtnOrdenNuevoAgregarPaciente);
            base.Controls.Add(this.label2);
            base.Controls.Add(this.BtnUIOrdenNuevo2);
            base.Controls.Add(this.label11);
            base.Controls.Add(this.label5);
            base.Controls.Add(this.ComboBoxMedico);
            base.Controls.Add(this.ComboBoxConsultorio);
            base.Controls.Add(this.CampSexo);
            base.Controls.Add(this.label6);
            base.Controls.Add(this.CheckBoxGestante);
            base.Controls.Add(this.label3);
            base.Controls.Add(this.CampBoleta);
            base.Controls.Add(this.PickerTime);
            base.Controls.Add(this.label1);
            base.Controls.Add(this.label7);
            base.Controls.Add(this.PanelBarTable);
            base.Controls.Add(this.CampUbicacion);
            base.Controls.Add(this.label12);
            base.Controls.Add(this.label9);
            base.Controls.Add(this.CampHistoria);
            base.Controls.Add(this.CampDni);
            base.Controls.Add(this.CampNombre);
            base.Controls.Add(this.dataGridView);
            base.Controls.Add(this.label10);
            base.Controls.Add(this.label8);
            base.Controls.Add(this.label4);
            base.Name = "PanelOrdenNuevo";
            base.Size = new Size(0x435, 0x228);
            this.PanelBarTable.ResumeLayout(false);
            this.PanelBarTable.PerformLayout();
            ((ISupportInitialize)this.dataGridView).EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }



        #endregion
        private Button BtnOrdenNuevoAgregarExamen;
        private Button BtnOrdenNuevoAgregarPaciente;
        private Button BtnOrdenNuevoCerrar;
        private Button BtnOrdenNuevoEliminarExamen;
        private ButtonUI BtnUIOrdenNuevo2;
        private TextBox CampBoleta;
        private Label CampDni;
        private Label CampHistoria;
        private Label CampNombre;
        private Label CampSexo;
        private Label CampUbicacion;
        private CheckBox CheckBoxGestante;
        private DataGridViewComboBoxColumn cobertura;
        private DataGridViewTextBoxColumn codigo;
        private ComboBox ComboBoxConsultorio;
        private ComboBox ComboBoxMedico;
        private ComboBox ComboExamen;
        private DataGridView dataGridView;
        private DataGridViewTextBoxColumn id;
        private DataGridViewTextBoxColumn idUnique;
        private Label label1;
        private Label label10;
        private Label label11;
        private Label label12;
        private Label label2;
        private Label label3;
        private Label label4;
        private Label label5;
        private Label label6;
        private Label label7;
        private Label label8;
        private Label label9;
        private Label LabelNombreExamen;
        private DataGridViewTextBoxColumn nombre;
        private Panel PanelBarTable;
        private DateTimePicker PickerTime;
        private ToolTip tip;


    }
}
