
using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;


namespace LabDesk.Code.Components.Actors.Paciente
{
    partial class PanelPacientePerfil
    {
        /// <summary> 
        /// Variable del diseñador necesaria.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Limpiar los recursos que se estén usando.
        /// </summary>
        /// <param name="disposing">true si los recursos administrados se deben desechar; false en caso contrario.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Código generado por el Diseñador de componentes

        /// <summary> 
        /// Método necesario para admitir el Diseñador. No se puede modificar
        /// el contenido de este método con el editor de código.
        /// </summary>

        private void InitializeComponent()
        {
            DataGridViewCellStyle style = new DataGridViewCellStyle();
            DataGridViewCellStyle style2 = new DataGridViewCellStyle();
            DataGridViewCellStyle style3 = new DataGridViewCellStyle();
            this.PanelBarTable = new Panel();
            this.ComboBoxOrden = new ComboBox();
            this.LabelOrden = new Label();
            this.ComboEstado = new ComboBox();
            this.BtnPacientePerfilPrint = new Button();
            this.PickerEnd = new DateTimePicker();
            this.PickerInit = new DateTimePicker();
            this.label1 = new Label();
            this.label2 = new Label();
            this.label3 = new Label();
            this.CampSexo = new Label();
            this.CampHistoria = new Label();
            this.CampDireccion = new Label();
            this.CampEdad = new Label();
            this.CampDni = new Label();
            this.CampNombre = new Label();
            this.DGVExamen = new DataGridView();
            this.Id = new DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn1 = new DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn2 = new DataGridViewTextBoxColumn();
            this.dataGridViewComboBoxColumn1 = new DataGridViewTextBoxColumn();
            this.lastModif = new DataGridViewTextBoxColumn();
            this.IdOrden = new DataGridViewTextBoxColumn();
            this.label11 = new Label();
            this.label12 = new Label();
            this.label13 = new Label();
            this.label14 = new Label();
            this.label15 = new Label();
            this.label16 = new Label();
            this.label17 = new Label();
            this.label18 = new Label();
            this.CampUbicacion = new Label();
            this.label5 = new Label();
            this.BtnPacientePerfilEdit = new Button();
            this.BtnPacientePerfilCerrar = new Button();
            this.PanelBarTable.SuspendLayout();
            ((ISupportInitialize)this.DGVExamen).BeginInit();
            base.SuspendLayout();
            this.PanelBarTable.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Top;
            this.PanelBarTable.BackColor = Color.SteelBlue;
            this.PanelBarTable.Controls.Add(this.ComboBoxOrden);
            this.PanelBarTable.Controls.Add(this.LabelOrden);
            this.PanelBarTable.Controls.Add(this.ComboEstado);
            this.PanelBarTable.Controls.Add(this.BtnPacientePerfilPrint);
            this.PanelBarTable.Controls.Add(this.PickerEnd);
            this.PanelBarTable.Controls.Add(this.PickerInit);
            this.PanelBarTable.Controls.Add(this.label1);
            this.PanelBarTable.Controls.Add(this.label2);
            this.PanelBarTable.Controls.Add(this.label3);
            this.PanelBarTable.Location = new Point(0x1f, 0xec);
            this.PanelBarTable.Margin = new Padding(0);
            this.PanelBarTable.Name = "PanelBarTable";
            this.PanelBarTable.Size = new Size(0x3f4, 0x29);
            this.PanelBarTable.TabIndex = 0x59;
            this.ComboBoxOrden.DropDownStyle = ComboBoxStyle.DropDownList;
            this.ComboBoxOrden.FlatStyle = FlatStyle.Flat;
            this.ComboBoxOrden.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.ComboBoxOrden.FormattingEnabled = true;
            this.ComboBoxOrden.Location = new Point(0x245, 9);
            this.ComboBoxOrden.Name = "ComboBoxOrden";
            this.ComboBoxOrden.Size = new Size(0x116, 0x18);
            this.ComboBoxOrden.TabIndex = 0x49;
            this.ComboBoxOrden.Visible = false;
            this.ComboBoxOrden.SelectedIndexChanged += new EventHandler(this.ComboBoxOrden_SelectedIndexChanged);
            this.LabelOrden.AutoSize = true;
            this.LabelOrden.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelOrden.ForeColor = SystemColors.Window;
            this.LabelOrden.Location = new Point(0x20e, 13);
            this.LabelOrden.Name = "LabelOrden";
            this.LabelOrden.Size = new Size(0x31, 0x10);
            this.LabelOrden.TabIndex = 0x48;
            this.LabelOrden.Text = "Orden:";
            this.LabelOrden.Visible = false;
            this.ComboEstado.DropDownStyle = ComboBoxStyle.DropDownList;
            this.ComboEstado.FlatStyle = FlatStyle.Flat;
            this.ComboEstado.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.ComboEstado.FormattingEnabled = true;
            this.ComboEstado.Location = new Point(0x178, 9);
            this.ComboEstado.Name = "ComboEstado";
            this.ComboEstado.Size = new Size(0x79, 0x18);
            this.ComboEstado.TabIndex = 0x45;
            this.ComboEstado.SelectedIndexChanged += new EventHandler(this.ComboEstado_SelectedIndexChanged);
            this.BtnPacientePerfilPrint.Anchor = AnchorStyles.Right | AnchorStyles.Bottom | AnchorStyles.Top;
            this.BtnPacientePerfilPrint.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.BtnPacientePerfilPrint.FlatAppearance.BorderSize = 0;
            this.BtnPacientePerfilPrint.FlatAppearance.CheckedBackColor = Color.DeepSkyBlue;
            this.BtnPacientePerfilPrint.FlatStyle = FlatStyle.Flat;
            this.BtnPacientePerfilPrint.Font = new Font("Segoe UI", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.BtnPacientePerfilPrint.ForeColor = SystemColors.Info;
            //this.BtnPacientePerfilPrint.Image = Resources.icon_printer;
            this.BtnPacientePerfilPrint.Location = new Point(0x3ce, 5);
            this.BtnPacientePerfilPrint.Name = "BtnPacientePerfilPrint";
            this.BtnPacientePerfilPrint.Size = new Size(0x20, 0x20);
            this.BtnPacientePerfilPrint.TabIndex = 0x47;
            this.BtnPacientePerfilPrint.UseVisualStyleBackColor = false;
            this.BtnPacientePerfilPrint.Visible = false;
            this.BtnPacientePerfilPrint.Click += new EventHandler(this.BtnPrint_Click);
            this.PickerEnd.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.PickerEnd.Format = DateTimePickerFormat.Short;
            this.PickerEnd.Location = new Point(0xcf, 10);
            this.PickerEnd.Name = "PickerEnd";
            this.PickerEnd.Size = new Size(0x61, 0x17);
            this.PickerEnd.TabIndex = 0x40;
            this.PickerEnd.ValueChanged += new EventHandler(this.PickerEnd_ValueChanged);
            this.PickerInit.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.PickerInit.Format = DateTimePickerFormat.Short;
            this.PickerInit.Location = new Point(0x3a, 10);
            this.PickerInit.MaxDate = new DateTime(0x83e, 12, 0x1f, 0, 0, 0, 0);
            this.PickerInit.MinDate = new DateTime(0x7e0, 10, 15, 0, 0, 0, 0);
            this.PickerInit.Name = "PickerInit";
            this.PickerInit.Size = new Size(0x62, 0x17);
            this.PickerInit.TabIndex = 0x41;
            this.PickerInit.Value = new DateTime(0x7e0, 10, 15, 15, 0x3b, 0x24, 0);
            this.PickerInit.ValueChanged += new EventHandler(this.PickerInit_ValueChanged);
            this.label1.AutoSize = true;
            this.label1.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label1.ForeColor = SystemColors.Window;
            this.label1.Location = new Point(8, 13);
            this.label1.Name = "label1";
            this.label1.Size = new Size(0x2f, 0x10);
            this.label1.TabIndex = 0x42;
            this.label1.Text = "Desde ";
            this.label2.AutoSize = true;
            this.label2.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label2.ForeColor = SystemColors.Window;
            this.label2.Location = new Point(0x142, 13);
            this.label2.Name = "label2";
            this.label2.Size = new Size(0x30, 0x10);
            this.label2.TabIndex = 0x44;
            this.label2.Text = "Estado:";
            this.label3.AutoSize = true;
            this.label3.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label3.ForeColor = SystemColors.Window;
            this.label3.Location = new Point(0xa5, 13);
            this.label3.Name = "label3";
            this.label3.Size = new Size(0x25, 0x10);
            this.label3.TabIndex = 0x43;
            this.label3.Text = "hasta";
            this.CampSexo.AutoSize = true;
            this.CampSexo.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.CampSexo.Location = new Point(0x2d2, 0x6c);
            this.CampSexo.Name = "CampSexo";
            this.CampSexo.Size = new Size(40, 0x10);
            this.CampSexo.TabIndex = 0x58;
            this.CampSexo.Text = "Alexis";
            this.CampHistoria.AutoSize = true;
            this.CampHistoria.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.CampHistoria.Location = new Point(0x14b, 0x6c);
            this.CampHistoria.Name = "CampHistoria";
            this.CampHistoria.Size = new Size(40, 0x10);
            this.CampHistoria.TabIndex = 0x57;
            this.CampHistoria.Text = "Alexis";
            this.CampDireccion.AutoSize = true;
            this.CampDireccion.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.CampDireccion.Location = new Point(0x69, 0x97);
            this.CampDireccion.Name = "CampDireccion";
            this.CampDireccion.Size = new Size(40, 0x10);
            this.CampDireccion.TabIndex = 0x56;
            this.CampDireccion.Text = "Alexis";
            this.CampEdad.AutoSize = true;
            this.CampEdad.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.CampEdad.Location = new Point(0x220, 0x6c);
            this.CampEdad.Name = "CampEdad";
            this.CampEdad.Size = new Size(40, 0x10);
            this.CampEdad.TabIndex = 0x55;
            this.CampEdad.Text = "Alexis";
            this.CampDni.AutoSize = true;
            this.CampDni.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.CampDni.Location = new Point(0x69, 0x6c);
            this.CampDni.Name = "CampDni";
            this.CampDni.Size = new Size(40, 0x10);
            this.CampDni.TabIndex = 0x54;
            this.CampDni.Text = "Alexis";
            this.CampNombre.AutoSize = true;
            this.CampNombre.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.CampNombre.Location = new Point(0x69, 0x41);
            this.CampNombre.Name = "CampNombre";
            this.CampNombre.Size = new Size(40, 0x10);
            this.CampNombre.TabIndex = 0x53;
            this.CampNombre.Text = "Alexis";
            this.DGVExamen.AllowUserToAddRows = false;
            this.DGVExamen.AllowUserToDeleteRows = false;
            this.DGVExamen.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Bottom | AnchorStyles.Top;
            this.DGVExamen.BackgroundColor = SystemColors.ScrollBar;
            this.DGVExamen.BorderStyle = BorderStyle.None;
            style.Alignment = DataGridViewContentAlignment.MiddleLeft;
            style.BackColor = SystemColors.Control;
            style.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            style.ForeColor = SystemColors.WindowText;
            style.SelectionBackColor = SystemColors.Highlight;
            style.SelectionForeColor = SystemColors.HighlightText;
            style.WrapMode = DataGridViewTriState.True;
            this.DGVExamen.ColumnHeadersDefaultCellStyle = style;
            this.DGVExamen.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            DataGridViewColumn[] dataGridViewColumns = new DataGridViewColumn[] { this.Id, this.dataGridViewTextBoxColumn1, this.dataGridViewTextBoxColumn2, this.dataGridViewComboBoxColumn1, this.lastModif, this.IdOrden };
            this.DGVExamen.Columns.AddRange(dataGridViewColumns);
            style2.Alignment = DataGridViewContentAlignment.MiddleLeft;
            style2.BackColor = SystemColors.Window;
            style2.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            style2.ForeColor = SystemColors.ControlText;
            style2.SelectionBackColor = SystemColors.Highlight;
            style2.SelectionForeColor = SystemColors.HighlightText;
            style2.WrapMode = DataGridViewTriState.False;
            this.DGVExamen.DefaultCellStyle = style2;
            this.DGVExamen.Location = new Point(0x1f, 0x115);
            this.DGVExamen.Margin = new Padding(0);
            this.DGVExamen.Name = "DGVExamen";
            this.DGVExamen.ReadOnly = true;
            style3.Alignment = DataGridViewContentAlignment.MiddleLeft;
            style3.BackColor = SystemColors.Control;
            style3.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            style3.ForeColor = SystemColors.WindowText;
            style3.SelectionBackColor = SystemColors.Highlight;
            style3.SelectionForeColor = SystemColors.HighlightText;
            style3.WrapMode = DataGridViewTriState.True;
            this.DGVExamen.RowHeadersDefaultCellStyle = style3;
            this.DGVExamen.Size = new Size(0x3f4, 250);
            this.DGVExamen.TabIndex = 0x52;
            this.Id.HeaderText = "ID";
            this.Id.Name = "Id";
            this.Id.ReadOnly = true;
            this.Id.Visible = false;
            this.dataGridViewTextBoxColumn1.HeaderText = "Codigo";
            this.dataGridViewTextBoxColumn1.Name = "dataGridViewTextBoxColumn1";
            this.dataGridViewTextBoxColumn1.ReadOnly = true;
            this.dataGridViewTextBoxColumn1.Resizable = DataGridViewTriState.False;
            this.dataGridViewTextBoxColumn1.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.dataGridViewTextBoxColumn1.Width = 90;
            this.dataGridViewTextBoxColumn2.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            this.dataGridViewTextBoxColumn2.HeaderText = "Examen";
            this.dataGridViewTextBoxColumn2.Name = "dataGridViewTextBoxColumn2";
            this.dataGridViewTextBoxColumn2.ReadOnly = true;
            this.dataGridViewTextBoxColumn2.Resizable = DataGridViewTriState.False;
            this.dataGridViewTextBoxColumn2.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.dataGridViewTextBoxColumn2.ToolTipText = "Abrir Examen";
            this.dataGridViewComboBoxColumn1.HeaderText = "Responsable";
            this.dataGridViewComboBoxColumn1.MinimumWidth = 200;
            this.dataGridViewComboBoxColumn1.Name = "dataGridViewComboBoxColumn1";
            this.dataGridViewComboBoxColumn1.ReadOnly = true;
            this.dataGridViewComboBoxColumn1.Resizable = DataGridViewTriState.False;
            this.dataGridViewComboBoxColumn1.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.dataGridViewComboBoxColumn1.Width = 200;
            this.lastModif.HeaderText = "Ultima Modificaci\x00f3n";
            this.lastModif.Name = "lastModif";
            this.lastModif.ReadOnly = true;
            this.lastModif.Width = 200;
            this.IdOrden.HeaderText = "IdOrden";
            this.IdOrden.Name = "IdOrden";
            this.IdOrden.ReadOnly = true;
            this.IdOrden.Visible = false;
            this.label11.AutoSize = true;
            this.label11.Font = new Font("Futura Bk BT", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label11.Location = new Point(0x1c, 0xc3);
            this.label11.Name = "label11";
            this.label11.Size = new Size(0xa1, 0x13);
            this.label11.TabIndex = 0x51;
            this.label11.Text = "Historia de Examenes";
            this.label12.AutoSize = true;
            this.label12.Font = new Font("Futura Bk BT", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label12.Location = new Point(0x1c, 0x1c);
            this.label12.Name = "label12";
            this.label12.Size = new Size(0x9f, 0x13);
            this.label12.TabIndex = 80;
            this.label12.Text = "Informaci\x00f3n Personal";
            this.label13.AutoSize = true;
            this.label13.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label13.Location = new Point(0x2a5, 0x6c);
            this.label13.Name = "label13";
            this.label13.Size = new Size(0x27, 0x10);
            this.label13.TabIndex = 0x4f;
            this.label13.Text = "Sexo:";
            this.label14.AutoSize = true;
            this.label14.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label14.Location = new Point(0x1f2, 0x6c);
            this.label14.Name = "label14";
            this.label14.Size = new Size(40, 0x10);
            this.label14.TabIndex = 0x4e;
            this.label14.Text = "Edad:";
            this.label15.AutoSize = true;
            this.label15.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label15.Location = new Point(0xe5, 0x6c);
            this.label15.Name = "label15";
            this.label15.Size = new Size(0x60, 0x10);
            this.label15.TabIndex = 0x4d;
            this.label15.Text = "Historia Clinica:";
            this.label16.AutoSize = true;
            this.label16.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label16.Location = new Point(0x1c, 0x6c);
            this.label16.Name = "label16";
            this.label16.Size = new Size(0x22, 0x10);
            this.label16.TabIndex = 0x4c;
            this.label16.Text = "DNI:";
            this.label17.AutoSize = true;
            this.label17.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label17.Location = new Point(0x1c, 0x97);
            this.label17.Name = "label17";
            this.label17.Size = new Size(0x41, 0x10);
            this.label17.TabIndex = 0x4b;
            this.label17.Text = "Direccion:";
            this.label18.AutoSize = true;
            this.label18.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label18.Location = new Point(0x1c, 0x41);
            this.label18.Name = "label18";
            this.label18.Size = new Size(0x3b, 0x10);
            this.label18.TabIndex = 0x4a;
            this.label18.Text = "Nombre:";
            this.CampUbicacion.AutoSize = true;
            this.CampUbicacion.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.CampUbicacion.Location = new Point(0x220, 0x97);
            this.CampUbicacion.Name = "CampUbicacion";
            this.CampUbicacion.Size = new Size(40, 0x10);
            this.CampUbicacion.TabIndex = 0x7f;
            this.CampUbicacion.Text = "Alexis";
            this.label5.AutoSize = true;
            this.label5.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label5.Location = new Point(0x1ce, 0x97);
            this.label5.Name = "label5";
            this.label5.Size = new Size(0x4c, 0x10);
            this.label5.TabIndex = 0x7e;
            this.label5.Text = "Dist./Sector:";
            this.BtnPacientePerfilEdit.Anchor = AnchorStyles.Right | AnchorStyles.Top;
            this.BtnPacientePerfilEdit.FlatAppearance.BorderColor = Color.DimGray;
            this.BtnPacientePerfilEdit.FlatAppearance.BorderSize = 0;
            this.BtnPacientePerfilEdit.FlatStyle = FlatStyle.Flat;
            this.BtnPacientePerfilEdit.Font = new Font("Futura Bk BT", 8.25f);
            this.BtnPacientePerfilEdit.ForeColor = SystemColors.Window;
            //this.BtnPacientePerfilEdit.Image = Resources.icon_edit;
            this.BtnPacientePerfilEdit.Location = new Point(0x3f5, 12);
            this.BtnPacientePerfilEdit.Margin = new Padding(0);
            this.BtnPacientePerfilEdit.Name = "BtnPacientePerfilEdit";
            this.BtnPacientePerfilEdit.Padding = new Padding(5);
            this.BtnPacientePerfilEdit.Size = new Size(20, 20);
            this.BtnPacientePerfilEdit.TabIndex = 0xd5;
            this.BtnPacientePerfilEdit.TextAlign = ContentAlignment.MiddleLeft;
            this.BtnPacientePerfilEdit.TextImageRelation = TextImageRelation.ImageBeforeText;
            this.BtnPacientePerfilEdit.UseVisualStyleBackColor = false;
            this.BtnPacientePerfilEdit.Click += new EventHandler(this.BtnEdit_Click);
            this.BtnPacientePerfilCerrar.Anchor = AnchorStyles.Right | AnchorStyles.Top;
            this.BtnPacientePerfilCerrar.FlatAppearance.BorderColor = Color.DimGray;
            this.BtnPacientePerfilCerrar.FlatAppearance.BorderSize = 0;
            this.BtnPacientePerfilCerrar.FlatStyle = FlatStyle.Flat;
            this.BtnPacientePerfilCerrar.Font = new Font("Futura Bk BT", 8.25f);
            this.BtnPacientePerfilCerrar.ForeColor = SystemColors.Window;
          //  this.BtnPacientePerfilCerrar.Image = Resources.icon_cerrar;
            this.BtnPacientePerfilCerrar.Location = new Point(0x412, 12);
            this.BtnPacientePerfilCerrar.Margin = new Padding(0);
            this.BtnPacientePerfilCerrar.Name = "BtnPacientePerfilCerrar";
            this.BtnPacientePerfilCerrar.Padding = new Padding(5);
            this.BtnPacientePerfilCerrar.Size = new Size(20, 20);
            this.BtnPacientePerfilCerrar.TabIndex = 0xd4;
            this.BtnPacientePerfilCerrar.TextAlign = ContentAlignment.MiddleLeft;
            this.BtnPacientePerfilCerrar.TextImageRelation = TextImageRelation.ImageBeforeText;
            this.BtnPacientePerfilCerrar.UseVisualStyleBackColor = false;
            this.BtnPacientePerfilCerrar.Click += new EventHandler(this.BtnCerrar_Click);
            base.AutoScaleMode = AutoScaleMode.None;
            this.BackColor = SystemColors.Window;
            base.Controls.Add(this.BtnPacientePerfilEdit);
            base.Controls.Add(this.BtnPacientePerfilCerrar);
            base.Controls.Add(this.CampUbicacion);
            base.Controls.Add(this.label5);
            base.Controls.Add(this.PanelBarTable);
            base.Controls.Add(this.CampSexo);
            base.Controls.Add(this.CampHistoria);
            base.Controls.Add(this.CampDireccion);
            base.Controls.Add(this.CampEdad);
            base.Controls.Add(this.CampDni);
            base.Controls.Add(this.CampNombre);
            base.Controls.Add(this.DGVExamen);
            base.Controls.Add(this.label11);
            base.Controls.Add(this.label12);
            base.Controls.Add(this.label13);
            base.Controls.Add(this.label14);
            base.Controls.Add(this.label15);
            base.Controls.Add(this.label16);
            base.Controls.Add(this.label17);
            base.Controls.Add(this.label18);
            base.Margin = new Padding(0);
            base.Name = "PanelPacientePerfil";
            base.Size = new Size(0x435, 0x228);
            base.Load += new EventHandler(this.PanelPerfil_Load);
            this.PanelBarTable.ResumeLayout(false);
            this.PanelBarTable.PerformLayout();
            ((ISupportInitialize)this.DGVExamen).EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }


        #endregion

        private Button BtnPacientePerfilCerrar;
        private Button BtnPacientePerfilEdit;
        private Button BtnPacientePerfilPrint;
        private Label CampDireccion;
        private Label CampDni;
        private Label CampEdad;
        private Label CampHistoria;
        private Label CampNombre;
        private Label CampSexo;
        private Label CampUbicacion;
        private ComboBox ComboBoxOrden;
        private ComboBox ComboEstado;
        private DataGridViewTextBoxColumn dataGridViewComboBoxColumn1;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn1;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn2;
        private DataGridView DGVExamen;
        private DataGridViewTextBoxColumn Id;
        private DataGridViewTextBoxColumn IdOrden;

        private Label label1;
        private Label label11;
        private Label label12;
        private Label label13;
        private Label label14;
        private Label label15;
        private Label label16;
        private Label label17;
        private Label label18;
        private Label label2;
        private Label label3;
        private Label label5;
        private Label LabelOrden;
        private DataGridViewTextBoxColumn lastModif;

        private Panel PanelBarTable;
        private DateTimePicker PickerEnd;
        private DateTimePicker PickerInit;
    }
}
