using LabDesk.Code.Base;
using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace LabDesk.Code.Components.Actors.Paciente
{
    partial class PanelPacienteNuevo
    {
        /// <summary> 
        /// Variable del diseñador necesaria.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Limpiar los recursos que se estén usando.
        /// </summary>
        /// <param name="disposing">true si los recursos administrados se deben desechar; false en caso contrario.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Código generado por el Diseñador de componentes

        /// <summary> 
        /// Método necesario para admitir el Diseñador. No se puede modificar
        /// el contenido de este método con el editor de código.
        /// </summary>

        private void InitializeComponent()
        {
            ComponentResourceManager manager = new ComponentResourceManager(typeof(PanelPacienteNuevo));
            this.panel2 = new Panel();
            this.CheckEstado = new CheckBox();
            this.BtnSave = new Button();
            this.panel4 = new Panel();
            this.LabelExamen = new Label();
            this.BtnClose = new Button();
            this.campFecha = new DateTimePicker();
            this.label10 = new Label();
            this.campHistoria = new TextBox();
            this.label9 = new Label();
            this.campDNI = new TextBox();
            this.comboSexo = new ComboBox();
            this.label6 = new Label();
            this.label2 = new Label();
            this.campDireccion = new TextBox();
            this.label4 = new Label();
            this.label5 = new Label();
            this.label3 = new Label();
            this.campNombre = new TextBox();
            this.label11 = new Label();
            this.campapellido2erno = new TextBox();
            this.campapellido1erno = new TextBox();
            this.label12 = new Label();
            this.panel1 = new Panel();
            this.label13 = new Label();
            this.label1 = new Label();
            this.ComboBoxDistrito = new ComboBox();
            this.label7 = new Label();
            this.ComboBoxSector = new ComboBox();
            this.label8 = new Label();
            this.BtnUIPacienteNuevo1 = new ButtonUI();
            this.BtnPerfilEditarGuardar = new Button();
            this.BtnPerfilEditarCerrar = new Button();
            this.label19 = new Label();
            this.label16 = new Label();
            this.label17 = new Label();
            this.label15 = new Label();
            this.label14 = new Label();
            this.panel2.SuspendLayout();
            this.panel4.SuspendLayout();
            this.panel1.SuspendLayout();
            base.SuspendLayout();
            this.panel2.BackColor = Color.DodgerBlue;
            this.panel2.Controls.Add(this.CheckEstado);
            this.panel2.Controls.Add(this.BtnSave);
            this.panel2.Location = new Point(0x52, -51);
            this.panel2.Margin = new Padding(3, 4, 3, 4);
            this.panel2.Name = "panel2";
            this.panel2.Size = new Size(0x1f9, 0x20);
            this.panel2.TabIndex = 0x62;
            this.CheckEstado.AutoSize = true;
            this.CheckEstado.FlatStyle = FlatStyle.Flat;
            this.CheckEstado.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.CheckEstado.ForeColor = SystemColors.Window;
            this.CheckEstado.Location = new Point(0x1a0, 5);
            this.CheckEstado.Name = "CheckEstado";
            this.CheckEstado.Size = new Size(0x55, 20);
            this.CheckEstado.TabIndex = 100;
            this.CheckEstado.Text = "Terminado";
            this.CheckEstado.UseVisualStyleBackColor = true;
            this.CheckEstado.Visible = false;
            this.BtnSave.AutoSize = true;
            this.BtnSave.FlatAppearance.BorderSize = 0;
            this.BtnSave.FlatStyle = FlatStyle.Flat;
          //  this.BtnSave.Image = Resources.icon_guardar;
            this.BtnSave.Location = new Point(3, 2);
            this.BtnSave.Margin = new Padding(3, 4, 3, 4);
            this.BtnSave.Name = "BtnSave";
            this.BtnSave.Size = new Size(0x1f, 0x1b);
            this.BtnSave.TabIndex = 0x4a;
            this.BtnSave.UseVisualStyleBackColor = true;
            this.BtnSave.Visible = false;
            this.panel4.BackColor = SystemColors.WindowFrame;
            this.panel4.Controls.Add(this.LabelExamen);
            this.panel4.Controls.Add(this.BtnClose);
            this.panel4.Location = new Point(0x52, -80);
            this.panel4.Margin = new Padding(3, 4, 3, 4);
            this.panel4.Name = "panel4";
            this.panel4.Size = new Size(0x1f9, 30);
            this.panel4.TabIndex = 100;
            this.LabelExamen.AutoSize = true;
            this.LabelExamen.Font = new Font("Futura Md BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelExamen.ForeColor = SystemColors.ControlLightLight;
            this.LabelExamen.Location = new Point(4, 5);
            this.LabelExamen.MaximumSize = new Size(450, 0);
            this.LabelExamen.Name = "LabelExamen";
            this.LabelExamen.Size = new Size(0x29, 0x10);
            this.LabelExamen.TabIndex = 0x4c;
            this.LabelExamen.Text = "Titulo";
            this.BtnClose.AutoSize = true;
            this.BtnClose.FlatAppearance.BorderSize = 0;
            this.BtnClose.FlatStyle = FlatStyle.Flat;
            this.BtnClose.Location = new Point(0x1d7, 0);
            this.BtnClose.Margin = new Padding(3, 4, 3, 4);
            this.BtnClose.Name = "BtnClose";
            this.BtnClose.Size = new Size(0x1f, 0x1b);
            this.BtnClose.TabIndex = 0x4b;
            this.BtnClose.UseVisualStyleBackColor = true;
            this.BtnClose.Visible = false;
            this.campFecha.Font = new Font("Futura Bk BT", 9.75f);
            this.campFecha.Format = DateTimePickerFormat.Short;
            this.campFecha.Location = new Point(180, 0x10f);
            this.campFecha.Name = "campFecha";
            this.campFecha.RightToLeftLayout = true;
            this.campFecha.Size = new Size(0xb1, 0x17);
            this.campFecha.TabIndex = 6;
            this.label10.AutoSize = true;
            this.label10.Font = new Font("Futura Bk BT", 9.75f);
            this.label10.Location = new Point(0x1d, 0x74);
            this.label10.Name = "label10";
            this.label10.Size = new Size(0x60, 0x10);
            this.label10.TabIndex = 0x77;
            this.label10.Text = "Historia Clinica:";
            this.campHistoria.Font = new Font("Futura Bk BT", 9.75f);
            this.campHistoria.Location = new Point(180, 0x71);
            this.campHistoria.MaxLength = 15;
            this.campHistoria.Name = "campHistoria";
            this.campHistoria.Size = new Size(0xb1, 0x17);
            this.campHistoria.TabIndex = 2;
            this.label9.AutoSize = true;
            this.label9.Font = new Font("Futura Bk BT", 9.75f);
            this.label9.Location = new Point(0x1d, 0x4c);
            this.label9.Name = "label9";
            this.label9.Size = new Size(0x22, 0x10);
            this.label9.TabIndex = 0x76;
            this.label9.Text = "DNI:";
            this.campDNI.Font = new Font("Futura Bk BT", 9.75f);
            this.campDNI.Location = new Point(180, 0x49);
            this.campDNI.MaxLength = 8;
            this.campDNI.Name = "campDNI";
            this.campDNI.Size = new Size(0xb1, 0x17);
            this.campDNI.TabIndex = 1;
            this.comboSexo.DropDownStyle = ComboBoxStyle.DropDownList;
            this.comboSexo.Font = new Font("Futura Bk BT", 9.75f);
            this.comboSexo.FormattingEnabled = true;
            this.comboSexo.Location = new Point(180, 0x139);
            this.comboSexo.Name = "comboSexo";
            this.comboSexo.Size = new Size(0xb1, 0x18);
            this.comboSexo.TabIndex = 7;
            this.label6.AutoSize = true;
            this.label6.Font = new Font("Futura Bk BT", 9.75f);
            this.label6.Location = new Point(0x1d, 0x18c);
            this.label6.Name = "label6";
            this.label6.Size = new Size(0x41, 0x10);
            this.label6.TabIndex = 0x6f;
            this.label6.Text = "Direccion:";
            this.label2.AutoSize = true;
            this.label2.Font = new Font("Futura Bk BT", 9.75f);
            this.label2.Location = new Point(0x1d, 0x9c);
            this.label2.Name = "label2";
            this.label2.Size = new Size(0x3b, 0x10);
            this.label2.TabIndex = 0x65;
            this.label2.Text = "Nombre:";
            this.campDireccion.Font = new Font("Futura Bk BT", 9.75f);
            this.campDireccion.Location = new Point(180, 0x189);
            this.campDireccion.MaxLength = 100;
            this.campDireccion.Name = "campDireccion";
            this.campDireccion.Size = new Size(0x176, 0x17);
            this.campDireccion.TabIndex = 8;
            this.label4.AutoSize = true;
            this.label4.Font = new Font("Futura Bk BT", 9.75f);
            this.label4.Location = new Point(0x1d, 0x114);
            this.label4.Name = "label4";
            this.label4.Size = new Size(0x84, 0x10);
            this.label4.TabIndex = 0x6b;
            this.label4.Text = "Fecha de Nacimiento:";
            this.label5.AutoSize = true;
            this.label5.Font = new Font("Futura Bk BT", 9.75f);
            this.label5.Location = new Point(0x1d, 0x13c);
            this.label5.Name = "label5";
            this.label5.Size = new Size(0x27, 0x10);
            this.label5.TabIndex = 0x6d;
            this.label5.Text = "Sexo:";
            this.label3.AutoSize = true;
            this.label3.Font = new Font("Futura Bk BT", 9.75f);
            this.label3.Location = new Point(0x1d, 0xec);
            this.label3.Name = "label3";
            this.label3.Size = new Size(110, 0x10);
            this.label3.TabIndex = 0x68;
            this.label3.Text = "Segundo Apellido:";
            this.campNombre.Font = new Font("Futura Bk BT", 9.75f);
            this.campNombre.Location = new Point(180, 0x99);
            this.campNombre.MaxLength = 100;
            this.campNombre.Name = "campNombre";
            this.campNombre.Size = new Size(0x176, 0x17);
            this.campNombre.TabIndex = 3;
            this.label11.AutoSize = true;
            this.label11.Font = new Font("Futura Bk BT", 9.75f);
            this.label11.Location = new Point(0x1d, 0xc4);
            this.label11.Name = "label11";
            this.label11.Size = new Size(0x63, 0x10);
            this.label11.TabIndex = 0x66;
            this.label11.Text = "Primer Apellido:";
            this.campapellido2erno.Font = new Font("Futura Bk BT", 9.75f);
            this.campapellido2erno.Location = new Point(180, 0xe9);
            this.campapellido2erno.MaxLength = 100;
            this.campapellido2erno.Name = "campapellido2erno";
            this.campapellido2erno.Size = new Size(0x176, 0x17);
            this.campapellido2erno.TabIndex = 5;
            this.campapellido1erno.Font = new Font("Futura Bk BT", 9.75f);
            this.campapellido1erno.Location = new Point(180, 0xc1);
            this.campapellido1erno.MaxLength = 100;
            this.campapellido1erno.Name = "campapellido1erno";
            this.campapellido1erno.Size = new Size(0x176, 0x17);
            this.campapellido1erno.TabIndex = 4;
            this.label12.AutoSize = true;
            this.label12.Font = new Font("Futura Bk BT", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label12.Location = new Point(0x1c, 0x1c);
            this.label12.Name = "label12";
            this.label12.Size = new Size(0x9f, 0x13);
            this.label12.TabIndex = 0x7a;
            this.label12.Text = "Informaci\x00f3n Personal";
            this.panel1.Anchor = AnchorStyles.Right | AnchorStyles.Bottom | AnchorStyles.Top;
            this.panel1.BorderStyle = BorderStyle.FixedSingle;
            this.panel1.Controls.Add(this.label13);
            this.panel1.Controls.Add(this.label1);
            this.panel1.Location = new Point(0x323, 0x49);
            this.panel1.Margin = new Padding(0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new Size(0xf2, 0x183);
            this.panel1.TabIndex = 0x7b;
            this.label13.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Bottom | AnchorStyles.Top;
            this.label13.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label13.Location = new Point(0x13, 50);
            this.label13.Name = "label13";
            this.label13.Size = new Size(0xcd, 0x109);
            this.label13.TabIndex = 0x7c;
//            this.label13.Text = manager.GetString("label13.Text");
            this.label1.AutoSize = true;
            this.label1.Font = new Font("Futura Bk BT", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label1.Location = new Point(0x13, 0x13);
            this.label1.Name = "label1";
            this.label1.Size = new Size(0xac, 0x13);
            this.label1.TabIndex = 0x7b;
            this.label1.Text = "Indicaciones Generales";
            this.ComboBoxDistrito.DropDownStyle = ComboBoxStyle.DropDownList;
            this.ComboBoxDistrito.Font = new Font("Futura Bk BT", 9.75f);
            this.ComboBoxDistrito.FormattingEnabled = true;
            this.ComboBoxDistrito.Location = new Point(180, 0x161);
            this.ComboBoxDistrito.Name = "ComboBoxDistrito";
            this.ComboBoxDistrito.Size = new Size(0xb1, 0x18);
            this.ComboBoxDistrito.TabIndex = 0x7d;
            this.label7.AutoSize = true;
            this.label7.Font = new Font("Futura Bk BT", 9.75f);
            this.label7.Location = new Point(0x1d, 0x164);
            this.label7.Name = "label7";
            this.label7.Size = new Size(0x66, 0x10);
            this.label7.TabIndex = 0x7e;
            this.label7.Text = "Distrito / Sector :";
            this.ComboBoxSector.DropDownStyle = ComboBoxStyle.DropDownList;
            this.ComboBoxSector.Font = new Font("Futura Bk BT", 9.75f);
            this.ComboBoxSector.FormattingEnabled = true;
            this.ComboBoxSector.Location = new Point(0x179, 0x161);
            this.ComboBoxSector.Name = "ComboBoxSector";
            this.ComboBoxSector.Size = new Size(0xb1, 0x18);
            this.ComboBoxSector.TabIndex = 0x7f;
            this.label8.AutoSize = true;
            this.label8.Font = new Font("Futura Bk BT", 9f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label8.Location = new Point(0x16a, 0x166);
            this.label8.Name = "label8";
            this.label8.Size = new Size(12, 15);
            this.label8.TabIndex = 0x80;
            this.label8.Text = "/";
            this.BtnUIPacienteNuevo1.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            this.BtnUIPacienteNuevo1.BackColor = SystemColors.ActiveCaptionText;
            this.BtnUIPacienteNuevo1.Location = new Point(0x3a5, 0x1e7);
            this.BtnUIPacienteNuevo1.Margin = new Padding(0);
            this.BtnUIPacienteNuevo1.Name = "BtnUIPacienteNuevo1";
            this.BtnUIPacienteNuevo1.Size = new Size(0x70, 40);
            this.BtnUIPacienteNuevo1.TabIndex = 0xd1;
            this.BtnPerfilEditarGuardar.Anchor = AnchorStyles.Right | AnchorStyles.Top;
            this.BtnPerfilEditarGuardar.AutoSize = true;
            this.BtnPerfilEditarGuardar.FlatAppearance.BorderSize = 0;
            this.BtnPerfilEditarGuardar.FlatStyle = FlatStyle.Flat;
           // this.BtnPerfilEditarGuardar.Image = Resources.icon_guardar;
            this.BtnPerfilEditarGuardar.Location = new Point(0x3f5, 11);
            this.BtnPerfilEditarGuardar.Margin = new Padding(3, 4, 3, 4);
            this.BtnPerfilEditarGuardar.Name = "BtnPerfilEditarGuardar";
            this.BtnPerfilEditarGuardar.Size = new Size(0x16, 0x16);
            this.BtnPerfilEditarGuardar.TabIndex = 0xa7;
            this.BtnPerfilEditarGuardar.UseVisualStyleBackColor = true;
            this.BtnPerfilEditarGuardar.Visible = false;
            this.BtnPerfilEditarCerrar.Anchor = AnchorStyles.Right | AnchorStyles.Top;
            this.BtnPerfilEditarCerrar.FlatAppearance.BorderColor = Color.DimGray;
            this.BtnPerfilEditarCerrar.FlatAppearance.BorderSize = 0;
            this.BtnPerfilEditarCerrar.FlatStyle = FlatStyle.Flat;
            this.BtnPerfilEditarCerrar.Font = new Font("Futura Bk BT", 8.25f);
            this.BtnPerfilEditarCerrar.ForeColor = SystemColors.Window;
            //this.BtnPerfilEditarCerrar.Image = Resources.icon_cerrar;
            this.BtnPerfilEditarCerrar.Location = new Point(0x412, 12);
            this.BtnPerfilEditarCerrar.Margin = new Padding(0);
            this.BtnPerfilEditarCerrar.Name = "BtnPerfilEditarCerrar";
            this.BtnPerfilEditarCerrar.Padding = new Padding(5);
            this.BtnPerfilEditarCerrar.Size = new Size(20, 20);
            this.BtnPerfilEditarCerrar.TabIndex = 210;
            this.BtnPerfilEditarCerrar.TextAlign = ContentAlignment.MiddleLeft;
            this.BtnPerfilEditarCerrar.TextImageRelation = TextImageRelation.ImageBeforeText;
            this.BtnPerfilEditarCerrar.UseVisualStyleBackColor = false;
            this.BtnPerfilEditarCerrar.Click += new EventHandler(this.BtnPerfilNuevoCerrar_Click);
            this.label19.AutoSize = true;
            this.label19.BackColor = Color.Transparent;
            this.label19.Font = new Font("Futura Bk BT", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label19.ForeColor = SystemColors.GrayText;
            this.label19.Location = new Point(560, 0xea);
            this.label19.Name = "label19";
            this.label19.Size = new Size(0x1a, 0x13);
            this.label19.TabIndex = 0xd7;
            this.label19.Text = "(*)";
            this.label16.AutoSize = true;
            this.label16.BackColor = Color.Transparent;
            this.label16.Font = new Font("Futura Bk BT", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label16.ForeColor = SystemColors.GrayText;
            this.label16.Location = new Point(560, 0xc2);
            this.label16.Name = "label16";
            this.label16.Size = new Size(0x1a, 0x13);
            this.label16.TabIndex = 0xd6;
            this.label16.Text = "(*)";
            this.label17.AutoSize = true;
            this.label17.BackColor = Color.Transparent;
            this.label17.Font = new Font("Futura Bk BT", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label17.ForeColor = SystemColors.GrayText;
            this.label17.Location = new Point(560, 0x9a);
            this.label17.Name = "label17";
            this.label17.Size = new Size(0x1a, 0x13);
            this.label17.TabIndex = 0xd5;
            this.label17.Text = "(*)";
            this.label15.AutoSize = true;
            this.label15.BackColor = Color.Transparent;
            this.label15.Font = new Font("Futura Bk BT", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label15.ForeColor = SystemColors.GrayText;
            this.label15.Location = new Point(0x16b, 0x72);
            this.label15.Name = "label15";
            this.label15.Size = new Size(0x1a, 0x13);
            this.label15.TabIndex = 0xd4;
            this.label15.Text = "(*)";
            this.label14.AutoSize = true;
            this.label14.BackColor = Color.Transparent;
            this.label14.Font = new Font("Futura Bk BT", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label14.ForeColor = SystemColors.GrayText;
            this.label14.Location = new Point(0x16b, 0x4a);
            this.label14.Name = "label14";
            this.label14.Size = new Size(0x1a, 0x13);
            this.label14.TabIndex = 0xd3;
            this.label14.Text = "(*)";
            base.AutoScaleMode = AutoScaleMode.None;
            this.BackColor = SystemColors.Window;
            base.Controls.Add(this.label19);
            base.Controls.Add(this.label16);
            base.Controls.Add(this.label17);
            base.Controls.Add(this.label15);
            base.Controls.Add(this.label14);
            base.Controls.Add(this.BtnPerfilEditarGuardar);
            base.Controls.Add(this.BtnPerfilEditarCerrar);
            base.Controls.Add(this.BtnUIPacienteNuevo1);
            base.Controls.Add(this.label8);
            base.Controls.Add(this.ComboBoxSector);
            base.Controls.Add(this.ComboBoxDistrito);
            base.Controls.Add(this.label7);
            base.Controls.Add(this.label12);
            base.Controls.Add(this.panel1);
            base.Controls.Add(this.campFecha);
            base.Controls.Add(this.label10);
            base.Controls.Add(this.campHistoria);
            base.Controls.Add(this.label9);
            base.Controls.Add(this.campDNI);
            base.Controls.Add(this.comboSexo);
            base.Controls.Add(this.label6);
            base.Controls.Add(this.label2);
            base.Controls.Add(this.campDireccion);
            base.Controls.Add(this.label4);
            base.Controls.Add(this.label5);
            base.Controls.Add(this.label3);
            base.Controls.Add(this.campNombre);
            base.Controls.Add(this.label11);
            base.Controls.Add(this.campapellido2erno);
            base.Controls.Add(this.campapellido1erno);
            base.Controls.Add(this.panel2);
            base.Controls.Add(this.panel4);
            base.Margin = new Padding(0);
            base.Name = "PanelPacienteNuevo";
            base.Size = new Size(0x435, 0x228);
            this.panel2.ResumeLayout(false);
            this.panel2.PerformLayout();
            this.panel4.ResumeLayout(false);
            this.panel4.PerformLayout();
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            base.ResumeLayout(false);
            base.PerformLayout();
        }


        #endregion

        private Button BtnClose;
        private Button BtnPerfilEditarCerrar;
        private Button BtnPerfilEditarGuardar;
        private Button BtnSave;
        private ButtonUI BtnUIPacienteNuevo1;
        private TextBox campapellido1erno;
        private TextBox campapellido2erno;
        private TextBox campDireccion;
        private TextBox campDNI;
        private DateTimePicker campFecha;
        private TextBox campHistoria;
        private TextBox campNombre;
        private CheckBox CheckEstado;
        private ComboBox ComboBoxDistrito;
        private ComboBox ComboBoxSector;
        private ComboBox comboSexo;
        private Label label1;
        private Label label10;
        private Label label11;
        private Label label12;
        private Label label13;
        private Label label14;
        private Label label15;
        private Label label16;
        private Label label17;
        private Label label19;
        private Label label2;
        private Label label3;
        private Label label4;
        private Label label5;
        private Label label6;
        private Label label7;
        private Label label8;
        private Label label9;
        private Label LabelExamen;
        private Panel panel1;
        private Panel panel2;
        private Panel panel4;

    }
}
