//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataManager.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProcAdd {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProcAdd() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataManager.Recursos.ProcAdd", typeof(ProcAdd).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD_CONSULTORIO.
        /// </summary>
        internal static string ADD_CONSULTORIO {
            get {
                return ResourceManager.GetString("ADD_CONSULTORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD_CUENTA.
        /// </summary>
        internal static string ADD_CUENTA {
            get {
                return ResourceManager.GetString("ADD_CUENTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD_DISTRITO.
        /// </summary>
        internal static string ADD_DISTRITO {
            get {
                return ResourceManager.GetString("ADD_DISTRITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD_EXAMEN.
        /// </summary>
        internal static string ADD_EXAMEN {
            get {
                return ResourceManager.GetString("ADD_EXAMEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD_GRUPO.
        /// </summary>
        internal static string ADD_GRUPO {
            get {
                return ResourceManager.GetString("ADD_GRUPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD_GRUPO_ITEM.
        /// </summary>
        internal static string ADD_GRUPO_ITEM {
            get {
                return ResourceManager.GetString("ADD_GRUPO_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD_ITEM.
        /// </summary>
        internal static string ADD_ITEM {
            get {
                return ResourceManager.GetString("ADD_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD_LISTAITEM.
        /// </summary>
        internal static string ADD_LISTAITEM {
            get {
                return ResourceManager.GetString("ADD_LISTAITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD_MEDICO.
        /// </summary>
        internal static string ADD_MEDICO {
            get {
                return ResourceManager.GetString("ADD_MEDICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD_ORDENCAB.
        /// </summary>
        internal static string ADD_ORDENCAB {
            get {
                return ResourceManager.GetString("ADD_ORDENCAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD_ORDENDET.
        /// </summary>
        internal static string ADD_ORDENDET {
            get {
                return ResourceManager.GetString("ADD_ORDENDET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD_PACIENTE.
        /// </summary>
        internal static string ADD_PACIENTE {
            get {
                return ResourceManager.GetString("ADD_PACIENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD_PLANTILLA.
        /// </summary>
        internal static string ADD_PLANTILLA {
            get {
                return ResourceManager.GetString("ADD_PLANTILLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD_PLANTILLA_ITEM.
        /// </summary>
        internal static string ADD_PLANTILLA_ITEM {
            get {
                return ResourceManager.GetString("ADD_PLANTILLA_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD_SECTOR.
        /// </summary>
        internal static string ADD_SECTOR {
            get {
                return ResourceManager.GetString("ADD_SECTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD_SEGURIDAD.
        /// </summary>
        internal static string ADD_SEGURIDAD {
            get {
                return ResourceManager.GetString("ADD_SEGURIDAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD_TARIFARIOCAB.
        /// </summary>
        internal static string ADD_TARIFARIOCAB {
            get {
                return ResourceManager.GetString("ADD_TARIFARIOCAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD_TARIFARIODET.
        /// </summary>
        internal static string ADD_TARIFARIODET {
            get {
                return ResourceManager.GetString("ADD_TARIFARIODET", resourceCulture);
            }
        }
    }
}
