//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataManager.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProcUpd {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProcUpd() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataManager.Recursos.ProcUpd", typeof(ProcUpd).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPD_CONSULTORIO.
        /// </summary>
        internal static string UPD_CONSULTORIO {
            get {
                return ResourceManager.GetString("UPD_CONSULTORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPD_CUENTA.
        /// </summary>
        internal static string UPD_CUENTA {
            get {
                return ResourceManager.GetString("UPD_CUENTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPD_CUENTA_CLAVE.
        /// </summary>
        internal static string UPD_CUENTA_CLAVE {
            get {
                return ResourceManager.GetString("UPD_CUENTA_CLAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPD_EXAMEN.
        /// </summary>
        internal static string UPD_EXAMEN {
            get {
                return ResourceManager.GetString("UPD_EXAMEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPD_EXAMEN_SINGLE.
        /// </summary>
        internal static string UPD_EXAMEN_SINGLE {
            get {
                return ResourceManager.GetString("UPD_EXAMEN_SINGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPD_MEDICO.
        /// </summary>
        internal static string UPD_MEDICO {
            get {
                return ResourceManager.GetString("UPD_MEDICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPD_MEDICO_HABIL.
        /// </summary>
        internal static string UPD_MEDICO_HABIL {
            get {
                return ResourceManager.GetString("UPD_MEDICO_HABIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPD_ORDENCAB.
        /// </summary>
        internal static string UPD_ORDENCAB {
            get {
                return ResourceManager.GetString("UPD_ORDENCAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPD_ORDENDET.
        /// </summary>
        internal static string UPD_ORDENDET {
            get {
                return ResourceManager.GetString("UPD_ORDENDET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPD_PACIENTE.
        /// </summary>
        internal static string UPD_PACIENTE {
            get {
                return ResourceManager.GetString("UPD_PACIENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPD_SEGURIDAD.
        /// </summary>
        internal static string UPD_SEGURIDAD {
            get {
                return ResourceManager.GetString("UPD_SEGURIDAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPD_TARIFARIO.
        /// </summary>
        internal static string UPD_TARIFARIO {
            get {
                return ResourceManager.GetString("UPD_TARIFARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPD_TARIFARIOCAB.
        /// </summary>
        internal static string UPD_TARIFARIOCAB {
            get {
                return ResourceManager.GetString("UPD_TARIFARIOCAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPD_TARIFARIOCAB_VIGENTE.
        /// </summary>
        internal static string UPD_TARIFARIOCAB_VIGENTE {
            get {
                return ResourceManager.GetString("UPD_TARIFARIOCAB_VIGENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPD_TARIFARIODET.
        /// </summary>
        internal static string UPD_TARIFARIODET {
            get {
                return ResourceManager.GetString("UPD_TARIFARIODET", resourceCulture);
            }
        }
    }
}
