using LabDesk.Code.Base;
using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace LabDesk.Code.Components.Laboratory.Exam
{
    partial class FormExamenEditor
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            ComponentResourceManager manager = new ComponentResourceManager(typeof(FormExamenEditor));
            this.label6 = new Label();
            this.label2 = new Label();
            this.label10 = new Label();
            this.label5 = new Label();
            this.label8 = new Label();
            this.label1 = new Label();
            this.DGVExamen = new DataGridView();
            this.Nombre = new DataGridViewTextBoxColumn();
            this.Estado = new DataGridViewTextBoxColumn();
            this.idExamen = new DataGridViewTextBoxColumn();
            this.label9 = new Label();
            this.CheckEstado = new CheckBox();
            this.BtnExamenEditarGuardar = new Button();
            this.PanelBarTable = new Panel();
            this.CampOrden = new Label();
            this.CampRegistro = new Label();
            this.PanelExamen = new Panel();
            this.PanelCerrado = new Panel();
            this.BtnUIExamenEditor1 = new ButtonUI();
            this.label11 = new Label();
            this.label4 = new Label();
            this.LabelModif = new Label();
            this.LabelUsuarioLast = new Label();
            this.BtnExamenEditarCerrar = new Button();
            this.LabelExamen = new Label();
            this.CampNombre = new Label();
            this.CampDni = new Label();
            this.CampEdad = new Label();
            this.CampHistoria = new Label();
            this.CampSexo = new Label();
            this.panel5 = new Panel();
            this.panel1 = new Panel();
            this.BtnUIExamenEditor2 = new ButtonUI();
            ((ISupportInitialize)this.DGVExamen).BeginInit();
            this.PanelBarTable.SuspendLayout();
            this.PanelExamen.SuspendLayout();
            this.PanelCerrado.SuspendLayout();
            this.panel1.SuspendLayout();
            base.SuspendLayout();
            this.label6.AutoSize = true;
            this.label6.BackColor = SystemColors.Window;
            this.label6.FlatStyle = FlatStyle.System;
            this.label6.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label6.Location = new Point(0x19, 0x71);
            this.label6.Name = "label6";
            this.label6.Size = new Size(40, 0x10);
            this.label6.TabIndex = 0x2c;
            this.label6.Text = "Edad:";
            this.label2.AutoSize = true;
            this.label2.BackColor = SystemColors.Window;
            this.label2.FlatStyle = FlatStyle.System;
            this.label2.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label2.Location = new Point(0xde, 0x71);
            this.label2.Name = "label2";
            this.label2.Size = new Size(0x27, 0x10);
            this.label2.TabIndex = 0x2a;
            this.label2.Text = "Sexo:";
            this.label10.AutoSize = true;
            this.label10.BackColor = SystemColors.Window;
            this.label10.FlatStyle = FlatStyle.System;
            this.label10.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label10.Location = new Point(0xde, 0x52);
            this.label10.Name = "label10";
            this.label10.Size = new Size(0x36, 0x10);
            this.label10.TabIndex = 40;
            this.label10.Text = "Historia:";
            this.label5.AutoSize = true;
            this.label5.BackColor = SystemColors.Window;
            this.label5.FlatStyle = FlatStyle.System;
            this.label5.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label5.Location = new Point(0x19, 0x35);
            this.label5.Name = "label5";
            this.label5.Size = new Size(0x3b, 0x10);
            this.label5.TabIndex = 0x24;
            this.label5.Text = "Nombre:";
            this.label8.AutoSize = true;
            this.label8.BackColor = SystemColors.Window;
            this.label8.FlatStyle = FlatStyle.System;
            this.label8.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label8.Location = new Point(0x19, 0x52);
            this.label8.Name = "label8";
            this.label8.Size = new Size(0x22, 0x10);
            this.label8.TabIndex = 0x26;
            this.label8.Text = "DNI:";
            this.label1.AutoSize = true;
            this.label1.Font = new Font("Futura Bk BT", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label1.Location = new Point(0x16, 0x13);
            this.label1.Name = "label1";
            this.label1.Size = new Size(0x8a, 0x13);
            this.label1.TabIndex = 0x3a;
            this.label1.Text = "Datos del Paciente";
            this.DGVExamen.AllowUserToAddRows = false;
            this.DGVExamen.AllowUserToDeleteRows = false;
            this.DGVExamen.BackgroundColor = SystemColors.ScrollBar;
            this.DGVExamen.BorderStyle = BorderStyle.None;
            this.DGVExamen.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            DataGridViewColumn[] dataGridViewColumns = new DataGridViewColumn[] { this.Nombre, this.Estado, this.idExamen };
            this.DGVExamen.Columns.AddRange(dataGridViewColumns);
            this.DGVExamen.Location = new Point(0x1a, 0xd5);
            this.DGVExamen.Margin = new Padding(0);
            this.DGVExamen.Name = "DGVExamen";
            this.DGVExamen.ReadOnly = true;
            this.DGVExamen.Size = new Size(0x16e, 0x124);
            this.DGVExamen.TabIndex = 70;
            this.Nombre.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            this.Nombre.HeaderText = "Nombre";
            this.Nombre.Name = "Nombre";
            this.Nombre.ReadOnly = true;
            this.Nombre.Resizable = DataGridViewTriState.False;
            this.Nombre.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.Nombre.ToolTipText = "Nombre de Examen";
            this.Estado.HeaderText = "Estado";
            this.Estado.Name = "Estado";
            this.Estado.ReadOnly = true;
            this.Estado.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.idExamen.HeaderText = "Column1";
            this.idExamen.Name = "idExamen";
            this.idExamen.ReadOnly = true;
            this.idExamen.Visible = false;
            this.label9.AutoSize = true;
            this.label9.Font = new Font("Futura Bk BT", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label9.Location = new Point(0x16, 0x97);
            this.label9.Name = "label9";
            this.label9.Size = new Size(0xa3, 0x13);
            this.label9.TabIndex = 0x47;
            this.label9.Text = "Carpeta de Examenes";
            this.CheckEstado.AutoSize = true;
            this.CheckEstado.FlatStyle = FlatStyle.Flat;
            this.CheckEstado.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.CheckEstado.ForeColor = SystemColors.InactiveCaptionText;
            this.CheckEstado.Location = new Point(330, 0x1f7);
            this.CheckEstado.Name = "CheckEstado";
            this.CheckEstado.RightToLeft = RightToLeft.Yes;
            this.CheckEstado.Size = new Size(0x55, 20);
            this.CheckEstado.TabIndex = 100;
            this.CheckEstado.Text = "Terminado";
            this.CheckEstado.UseVisualStyleBackColor = true;
            this.CheckEstado.Visible = false;
            this.CheckEstado.CheckedChanged += new EventHandler(this.CheckEstado_CheckedChanged);
            this.BtnExamenEditarGuardar.AutoSize = true;
            this.BtnExamenEditarGuardar.FlatAppearance.BorderSize = 0;
            this.BtnExamenEditarGuardar.FlatStyle = FlatStyle.Flat;
            // this.BtnExamenEditarGuardar.Image = Resources.icon_guardar;
            this.BtnExamenEditarGuardar.Location = new Point(0x16a, 7);
            this.BtnExamenEditarGuardar.Margin = new Padding(3, 4, 3, 4);
            this.BtnExamenEditarGuardar.Name = "BtnExamenEditarGuardar";
            this.BtnExamenEditarGuardar.Size = new Size(0x1f, 0x1b);
            this.BtnExamenEditarGuardar.TabIndex = 0x4a;
            this.BtnExamenEditarGuardar.UseVisualStyleBackColor = true;
            this.BtnExamenEditarGuardar.Visible = false;
            this.BtnExamenEditarGuardar.Click += new EventHandler(this.BtnSave_Click);
            this.PanelBarTable.BackColor = Color.SteelBlue;
            this.PanelBarTable.Controls.Add(this.CampOrden);
            this.PanelBarTable.Controls.Add(this.CampRegistro);
            this.PanelBarTable.Location = new Point(0x1a, 0xb5);
            this.PanelBarTable.Margin = new Padding(0);
            this.PanelBarTable.Name = "PanelBarTable";
            this.PanelBarTable.Size = new Size(0x16e, 0x20);
            this.PanelBarTable.TabIndex = 0x5c;
            this.CampOrden.AutoSize = true;
            this.CampOrden.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.CampOrden.ForeColor = SystemColors.ControlLightLight;
            this.CampOrden.Location = new Point(8, 8);
            this.CampOrden.Name = "CampOrden";
            this.CampOrden.Size = new Size(0x7e, 0x10);
            this.CampOrden.TabIndex = 0x66;
            this.CampOrden.Text = "Orden 21241 - 123";
            this.CampRegistro.AutoSize = true;
            this.CampRegistro.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.CampRegistro.ForeColor = SystemColors.ControlLightLight;
            this.CampRegistro.Location = new Point(0x11c, 8);
            this.CampRegistro.Name = "CampRegistro";
            this.CampRegistro.Size = new Size(0x42, 0x10);
            this.CampRegistro.TabIndex = 0x65;
            this.CampRegistro.Text = "10/15/15";
            this.PanelExamen.Controls.Add(this.PanelCerrado);
            this.PanelExamen.Controls.Add(this.LabelModif);
            this.PanelExamen.Location = new Point(0x11, 0x2a);
            this.PanelExamen.Margin = new Padding(0);
            this.PanelExamen.Name = "PanelExamen";
            this.PanelExamen.Size = new Size(0x19b, 0x1ca);
            this.PanelExamen.TabIndex = 0x5d;
            this.PanelCerrado.BackColor = Color.White;
            this.PanelCerrado.BorderStyle = BorderStyle.FixedSingle;
            this.PanelCerrado.Controls.Add(this.BtnUIExamenEditor1);
            this.PanelCerrado.Controls.Add(this.label11);
            this.PanelCerrado.Controls.Add(this.label4);
            this.PanelCerrado.Location = new Point(0x27, 0x8e);
            this.PanelCerrado.Name = "PanelCerrado";
            this.PanelCerrado.Size = new Size(0x142, 0xb3);
            this.PanelCerrado.TabIndex = 0;
            this.PanelCerrado.Visible = false;
            this.BtnUIExamenEditor1.AutoSize = true;
            this.BtnUIExamenEditor1.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.BtnUIExamenEditor1.BackColor = SystemColors.ActiveCaptionText;
            this.BtnUIExamenEditor1.Location = new Point(0x69, 0x6d);
            this.BtnUIExamenEditor1.Margin = new Padding(0);
            this.BtnUIExamenEditor1.Name = "BtnUIExamenEditor1";
            this.BtnUIExamenEditor1.Size = new Size(0x70, 40);
            this.BtnUIExamenEditor1.TabIndex = 0x4b;
            this.label11.AutoSize = true;
            this.label11.BackColor = SystemColors.Window;
            this.label11.FlatStyle = FlatStyle.System;
            this.label11.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label11.Location = new Point(0x1b, 0x3b);
            this.label11.Name = "label11";
            this.label11.Size = new Size(0x10c, 0x20);
            this.label11.TabIndex = 0x4a;
            this.label11.Text = "Si deseas volver habilitar el examen necesitas \r\nla autorizacion del administrador.";
            this.label11.TextAlign = ContentAlignment.MiddleCenter;
            this.label4.AutoSize = true;
            this.label4.Font = new Font("Futura Bk BT", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label4.Location = new Point(0x77, 0x1a);
            this.label4.Name = "label4";
            this.label4.Size = new Size(0x55, 0x13);
            this.label4.TabIndex = 0x48;
            this.label4.Text = "Terminado";
            this.LabelModif.AutoSize = true;
            this.LabelModif.Font = new Font("Futura Bk BT", 9f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelModif.Location = new Point(13, 0x1e3);
            this.LabelModif.Name = "LabelModif";
            this.LabelModif.Size = new Size(0x65, 15);
            this.LabelModif.TabIndex = 100;
            this.LabelModif.Text = "Ult. modificaci\x00f3n:";
            this.LabelUsuarioLast.AutoSize = true;
            this.LabelUsuarioLast.Font = new Font("Futura Bk BT", 9f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelUsuarioLast.Location = new Point(14, 0x1fa);
            this.LabelUsuarioLast.Name = "LabelUsuarioLast";
            this.LabelUsuarioLast.Size = new Size(40, 15);
            this.LabelUsuarioLast.TabIndex = 0x65;
            this.LabelUsuarioLast.Text = "label3";
            this.BtnExamenEditarCerrar.AutoSize = true;
            this.BtnExamenEditarCerrar.FlatAppearance.BorderSize = 0;
            this.BtnExamenEditarCerrar.FlatStyle = FlatStyle.Flat;
            //this.BtnExamenEditarCerrar.Image = Resources.icon_cerrar;
            this.BtnExamenEditarCerrar.Location = new Point(0x18c, 9);
            this.BtnExamenEditarCerrar.Margin = new Padding(0);
            this.BtnExamenEditarCerrar.Name = "BtnExamenEditarCerrar";
            this.BtnExamenEditarCerrar.Size = new Size(0x16, 0x16);
            this.BtnExamenEditarCerrar.TabIndex = 0x4b;
            this.BtnExamenEditarCerrar.UseVisualStyleBackColor = true;
            this.BtnExamenEditarCerrar.Visible = false;
            this.BtnExamenEditarCerrar.Click += new EventHandler(this.BtnClose_Click);
            this.LabelExamen.AutoSize = true;
            this.LabelExamen.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelExamen.ForeColor = SystemColors.Desktop;
            this.LabelExamen.Location = new Point(11, 12);
            this.LabelExamen.MaximumSize = new Size(450, 0);
            this.LabelExamen.Name = "LabelExamen";
            this.LabelExamen.Size = new Size(0x26, 0x10);
            this.LabelExamen.TabIndex = 0x4c;
            this.LabelExamen.Text = "Titulo";
            this.CampNombre.AutoSize = true;
            this.CampNombre.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.CampNombre.Location = new Point(0x55, 0x35);
            this.CampNombre.Name = "CampNombre";
            this.CampNombre.Size = new Size(0x2b, 0x10);
            this.CampNombre.TabIndex = 0x5f;
            this.CampNombre.Text = "label3";
            this.CampDni.AutoSize = true;
            this.CampDni.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.CampDni.Location = new Point(0x55, 0x52);
            this.CampDni.Name = "CampDni";
            this.CampDni.Size = new Size(0x33, 0x10);
            this.CampDni.TabIndex = 0x60;
            this.CampDni.Text = "label11";
            this.CampEdad.AutoSize = true;
            this.CampEdad.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.CampEdad.Location = new Point(0x55, 0x71);
            this.CampEdad.Name = "CampEdad";
            this.CampEdad.Size = new Size(0x33, 0x10);
            this.CampEdad.TabIndex = 0x61;
            this.CampEdad.Text = "label12";
            this.CampHistoria.AutoSize = true;
            this.CampHistoria.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.CampHistoria.Location = new Point(0x128, 0x52);
            this.CampHistoria.Name = "CampHistoria";
            this.CampHistoria.Size = new Size(0x33, 0x10);
            this.CampHistoria.TabIndex = 0x62;
            this.CampHistoria.Text = "label14";
            this.CampSexo.AutoSize = true;
            this.CampSexo.Font = new Font("Futura Bk BT", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.CampSexo.Location = new Point(0x128, 0x71);
            this.CampSexo.Name = "CampSexo";
            this.CampSexo.Size = new Size(0x33, 0x10);
            this.CampSexo.TabIndex = 0x63;
            this.CampSexo.Text = "label15";
            this.panel5.BackColor = SystemColors.ScrollBar;
            this.panel5.Location = new Point(0x1a2, 3);
            this.panel5.Margin = new Padding(3, 4, 3, 4);
            this.panel5.Name = "panel5";
            this.panel5.Size = new Size(1, 580);
            this.panel5.TabIndex = 0x4a;
            this.panel1.BackColor = Color.LemonChiffon;
            this.panel1.BorderStyle = BorderStyle.FixedSingle;
            this.panel1.Controls.Add(this.LabelUsuarioLast);
            this.panel1.Controls.Add(this.PanelExamen);
            this.panel1.Controls.Add(this.BtnExamenEditarCerrar);
            this.panel1.Controls.Add(this.LabelExamen);
            this.panel1.Controls.Add(this.CheckEstado);
            this.panel1.Controls.Add(this.BtnExamenEditarGuardar);
            this.panel1.Location = new Point(0x1ba, 0x13);
            this.panel1.Margin = new Padding(0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new Size(430, 540);
            this.panel1.TabIndex = 100;
            this.BtnUIExamenEditor2.BackColor = SystemColors.ActiveCaptionText;
            this.BtnUIExamenEditor2.Location = new Point(280, 520);
            this.BtnUIExamenEditor2.Margin = new Padding(0);
            this.BtnUIExamenEditor2.Name = "BtnUIExamenEditor2";
            this.BtnUIExamenEditor2.Size = new Size(0x70, 40);
            this.BtnUIExamenEditor2.TabIndex = 0x65;
            base.AutoScaleDimensions = new SizeF(7f, 17f);
            base.AutoScaleMode = AutoScaleMode.Font;
            this.BackColor = SystemColors.Window;
            base.ClientSize = new Size(0x382, 0x246);
            base.Controls.Add(this.BtnUIExamenEditor2);
            base.Controls.Add(this.panel1);
            base.Controls.Add(this.CampSexo);
            base.Controls.Add(this.CampHistoria);
            base.Controls.Add(this.CampEdad);
            base.Controls.Add(this.CampDni);
            base.Controls.Add(this.CampNombre);
            base.Controls.Add(this.PanelBarTable);
            base.Controls.Add(this.panel5);
            base.Controls.Add(this.label9);
            base.Controls.Add(this.DGVExamen);
            base.Controls.Add(this.label1);
            base.Controls.Add(this.label6);
            base.Controls.Add(this.label2);
            base.Controls.Add(this.label10);
            base.Controls.Add(this.label5);
            base.Controls.Add(this.label8);
            this.Font = new Font("Segoe UI", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            //            base.Icon = (Icon)manager.GetObject("$this.Icon");
            base.Margin = new Padding(3, 4, 3, 4);
            base.MaximizeBox = false;
            base.Name = "FormExamenEditor";
            base.ShowInTaskbar = false;
            base.StartPosition = FormStartPosition.CenterParent;
            this.Text = "Formato de Examen";
            base.Load += new EventHandler(this.formExamenGeneral_Load);
            ((ISupportInitialize)this.DGVExamen).EndInit();
            this.PanelBarTable.ResumeLayout(false);
            this.PanelBarTable.PerformLayout();
            this.PanelExamen.ResumeLayout(false);
            this.PanelExamen.PerformLayout();
            this.PanelCerrado.ResumeLayout(false);
            this.PanelCerrado.PerformLayout();
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            base.ResumeLayout(false);
            base.PerformLayout();
        }


        #endregion
        private Button BtnExamenEditarCerrar;
        private Button BtnExamenEditarGuardar;
        private ButtonUI BtnUIExamenEditor1;
        private ButtonUI BtnUIExamenEditor2;
        private Label CampDni;
        private Label CampEdad;
        private Label CampHistoria;
        private Label CampNombre;
        private Label CampOrden;
        private Label CampRegistro;
        private Label CampSexo;
        private CheckBox CheckEstado;
        private DataGridView DGVExamen;
        private DataGridViewTextBoxColumn Estado;
        private DataGridViewTextBoxColumn idExamen;
        private Label label1;
        private Label label10;
        private Label label11;
        private Label label2;
        private Label label4;
        private Label label5;
        private Label label6;
        private Label label8;
        private Label label9;
        private Label LabelExamen;
        private Label LabelModif;
        private Label LabelUsuarioLast;
        private DataGridViewTextBoxColumn Nombre;
        private Panel panel1;
        private Panel panel5;
        private Panel PanelBarTable;
        private Panel PanelCerrado;
        private Panel PanelExamen;

    }
}